### PR TITLE
Decrease jupyter_core floor, cap nbclient for 3.7

### PR DESCRIPTION
**Pull request by kevin-bates**
As discussed in #3069, **conda** installs of Elyra will fail because the dependency of `jupyter_core >= 4.11.2` cannot be resolved.  This is because [conda removed support for Python 3.7 last August](https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7).  

This pull request will allow for conda installations of Elyra to succeed, albeit supporting versions of `jupyter_core <= 4.11.1`.  This change also resulted in capping `nbclient <= 0.7.0` for Python 3.7 since more recent versions of `nbclient` require `jupyter_core >= 4.12`.

Resolves: #3069 
Signed-off-by: Kevin Bates <kbates4@gmail.com>

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akchinSTC** [comment]
We can keep this open for discussion tomorrow at scrum, and close when necessary

**Comment by lresende** [comment]
Should we just remove support for Python 3.7?

**Comment by kevin-bates** [comment]
> Should we just remove support for Python 3.7?

I agree.  I think the bigger question is in what release can/should this removal occur in - 3.15 or 4.0?

**Comment by kevin-bates** [comment]
We should still merge this PR since it's limiting functionality on python releases > 3.7.  We can talk about dropping 3.7 independently.

**Review by akchinSTC — APPROVED** [review]

**Pull request merged**
