### PR TITLE
Re-add resuse support

### LINKED ISSUE #1161: Add support for jupyter-resource-usage
jupyter-resource-usage, previously nbresuse, has moved it's jupyterlab UI out of core and into a separate extension as of lab 3.0. Previously we enabled the UI by adding a dependency on the notebook server extension via our setup.py

Once a new version of jupyter-resource-usage including the labextension is released we should add the extension to elyra in the same way as we do the git extension

https://github.com/jupyter-server/jupyter-resource-usage

### PR DESCRIPTION
**Pull request by ajbozarth**
Fixes #1161 

nbresuse UI code was moved from core lab into an extension within the api, which was renamed and moved to the juoyter-server org. In order to keep the UI in Elyra we need to add it manually like we do git

Also fix some miswritten build lines for lsp support

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
How easy would be to enable CPU usage tracking as well?

**Comment by lresende** [comment]
Also, do we need to enable the extension as we do with the others at https://github.com/elyra-ai/elyra/tree/master/etc/config/jupyter_server_config.d. It does seem that it gets enabled by the pip install, but just in case...

**Comment by ajbozarth** [comment]
> Also, do we need to enable the extension as we do with the others at https://github.com/elyra-ai/elyra/tree/master/etc/config/jupyter_server_config.d. It does seem that it gets enabled by the pip install, but just in case...

I'll add it

> How easy would be to enable CPU usage tracking as well?

I'll take a quick look and see how trivial or non-trivial this is, iirc it was non-trivial when it was in core

**Comment by ajbozarth** [comment]
@lresende added the config json file, but as for CPU tracking, it's not even in the lab extension currently. So it's non-trivial, but we could contribute it to the lab extension ourselves if we want to. It wouldn't be very difficult add, but It would still take a non-trivial amount of time

**Review by lresende — APPROVED** [review]
LGTM

**Pull request merged**
