### PR TITLE
Update to canvas version 10.1.0

### PR DESCRIPTION
**Pull request by lresende**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
With these updates, the dark mode still needs some TLC:

See node properties below:

image

**Comment by bourdakos1** [comment]
@lresende should we make this PR on `pipeline-editor` instead?

**Comment by lresende** [comment]
@bourdakos1 while the pipeline-editor is not in use by the elyra pipeline editor extension, we need to add this on both sides.

**Comment by bourdakos1** [comment]
does anyone have a screenshot of what this looked like pre-update in darkmode?

**Comment by karlaspuldaro** [comment]
@bourdakos1 there's a screenshot is this PR https://github.com/elyra-ai/elyra/pull/1328

**Comment by bourdakos1** [comment]
thank you :)

**Comment by bourdakos1** [comment]
@lresende there isn't a great fix for this aside from some css hacks. This shouldn't be an issue when updating in `pipeline-editor` is there a reason we need to update to `10.1.0` now?

**Comment by lresende** [comment]
Thanks @bourdakos1, it's ok to have the hack until we move to pipeline-editor.

**Comment by lresende** [comment]
BTW, tested the fix and looks great now in both light and dark mode.

**Pull request merged**
