### PR TITLE
Migrate to the latest version of canvas

### LINKED ISSUE #645: Migrate to latest Elyra Canvas release

### PR DESCRIPTION
**Pull request by vabarbosa**
Migrate to the latest canvas version

- [x] Upgrade `@elyra/canvas` (from **6.1.23** to **8.0.32**)
- [x] Resolve breaking changes
- [x] Clean-up the UI
- [x] Verify ui tests
- [x] Update documentation screenshots
- Confirm canvas upgrade fixes issues:
    - ~~#750 ([part 2](https://github.com/elyra-ai/elyra/issues/750#issuecomment-657894923))~~ // will be resolved in canvas 9.0.x
    - [x] [icon svg support](https://github.com/elyra-ai/elyra/issues/733#issuecomment-656345530)
    - [x] #386
- Merge (upcoming) Pipeline editor PRs: 
    - [x] #741
    - ~~#744~~ // will be merged after this PR
    - [x] #750 ([part 1](https://github.com/elyra-ai/elyra/issues/750#issuecomment-657894923))
    - ~~#752~~ // may be merged after this PR

Changes

- per @elyra/canvas release 7.0.5
    - Updated dependency `react-intl` (^3.0.0) 
    - Added dependency `react-redux` (^7.0.0)
- per @elyra/canvas release 8.0.1
    - Updated CSS class names and styling
    - Placed `<CommonCanvas>` inside a `<IntlProvider>`
    - Removed `toolbarMenuActionHandler`. Handling of these actions moved to the `editActionHandler`
    - Removed `contextMenuActionHandler`. Handling of these actions moved to the `editActionHandler`.
    - Renamed `addComment` action to `createAutoComment`
    - Renamed `delete` action to `deleteSelectedObjects`
- per @elyra/canvas release 8.0.2
    - Added config `createSupernode` // user can disable creation of supernodes via configuration parameter
- per @elyra/canvas release 8.0.4
    - Added config `enableInsertNodeDroppedOnLink` // user can drag nodes from the palette and drop them onto existing links in the flow which causes the node to be inserted between the two nodes joined by the link

- Update [screenshots in documentation](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html)

Fixes #645
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by vabarbosa** [comment]
all the major work is dont here and it is basically ready for reviews. 

what left is to merge with #744 and #752 once those are ready. 
the [second part of #750](https://github.com/elyra-ai/elyra/issues/750#issuecomment-657894923) cannot be confirmed as it was [addressed in canvas yesterday](https://github.com/elyra-ai/canvas/issues/162) and won't be available until next canvas release.

**Comment by marthacryan** [comment]
Just tried this out locally and it looks great! So sleek! For those who don't have time to check out the PR locally this is what the new canvas looks like:
image

As for #744, I think actually it might be a good idea to merge this PR first, because I think there's a handler in the newer version of canvas that would simplify that PR (`beforeEditActionHandler`). 

We'll also need to change the pipeline documentation images to use the new interface.

**Comment by vabarbosa** [comment]
> Just tried this out locally and it looks great! So sleek! For those who don't have time to check out the PR locally this is what the new canvas looks like:
> 
> As for #744, I think actually it might be a good idea to merge this PR first, because I think there's a handler in the newer version of canvas that would simplify that PR (`beforeEditActionHandler`).
> 
> We'll also need to update the pipeline documentation images to use the new interface.

thanks for the reminder. i'll update to documentation images. this can be merged first if it is going to simplify #744

**Comment by vabarbosa** [comment]
this PR is good to go for `@elyra/canvas` v8.0.32.
however, v9 has just been published. i will upgrade to v9 instead and resolve any issues that may arise.

**Comment by marthacryan** [comment]
@vabarbosa Also, feel free to merge this before #752 merges as well and I can rebase. It seems like there's more to discuss on that PR than there is here.

**Comment by ajbozarth** [comment]
I'll be reviewing this early this afternoon, will post code and UX reviews as I finish each

**Comment by vabarbosa** [comment]
> Code and UX LGTM but I found some UI issues on Safari (surprise surprise Safari again >.<). I've attached screen shots of the oddities below:
> As you can see some of the borders and mouse over are missing or misaligned. No idea why it is like this on Safari and not Chrome.

thanks, Safari discrepancies should be resolved.

**Pull request merged**
