### PR TITLE
Initialize component defaults when double clicking palette nodes

### LINKED ISSUE #1877: VPE node validation issues
**Describe the issue**
A clear and concise description of what the issue is.

validation

**To Reproduce**
1. Create a KFP pipeline
2. Add custom component to canvas
3. Hover over node; observe the [mostly incorrect] validation errors

### PR DESCRIPTION
**Pull request by bourdakos1**
Fixes #1877.

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
I know we are waiting for the new version of pipeline editor, but can this get out of draft so I can move it once it's available.

**Review by marthacryan — APPROVED** [review]
Code LGTM and tested locally with elyra-ai/pipeline-editor#145

**Comment by bourdakos1** [comment]
@lresende i haven’t actually verified that it works with the pipeline-editor changes, but it apparently does so I will remove draft

**Comment by bourdakos1** [comment]
Before merging we should add a test case for:
- double clicking palette 
- dragging from palette
- Dragging from file explorer
- Right click add from file explorer

**Comment by ptitzler** [comment]
> add a test case for:

and  right click (on canvas) > "new node from file"

**Comment by bourdakos1** [comment]
switching to draft until tests added

**Pull request merged**
