### PR TITLE
Update Apache Airflow jinja template DAG creation logic

### PR DESCRIPTION
**Pull request by akchinSTC**
Fix to include runtime image parameter in notebook_op

image

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by ptitzler — CHANGES_REQUESTED** [review]
DAG execution now fails with

```
Broken DAG: [/opt/airflow/dags/hello-generic-world-0722114004.py] The key has to be a string
```

**Comment by akchinSTC** [comment]
> DAG execution now fails with
> 
> ```
> Broken DAG: [/opt/airflow/dags/hello-generic-world-0722114004.py] The key has to be a string
> ```

this is due to incorrect R&R in the template. parsing issues should be resolved now, ran noaa pipeline test on teacloth and its seems to be running now, albeit very slow today for some reason

**Review by ptitzler — APPROVED** [review]
LGTM

**Review by kiersten-stokes — APPROVED** [review]
LGTM!

**Pull request merged**
