### PR TITLE
Update ExpandableErrorDialog to use ExpandableComponent

### LINKED ISSUE #403: Reuse ExpandableComponent in SubmissionHandler
`ExpandableComponent` is a reusable react component created for code snippets display, that takes a display name and a react element with extra info that is displayed upon expand button click event. 
It is currently located in `packages/code-snippets/`
A similar usage would be in SubmissionHandler `showDialog()`
We should move ExpandableComponent to packages/application or to some util folder, and also integrate it to SubmissionHandler.

### PR DESCRIPTION
**Pull request by vabarbosa**
Updated the `ExpandableErrorDialog` to reuse  the `ExpandableComponent` component instead of implementing its own expandable area

Fixes #403

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
Code looks good on initial read, I'll check this out and play with it as soon as I have time tomorrow

**Comment by karlaspuldaro** [comment]
I tested this locally and had some questions.
I couldn't test anything where msg is super long, is max-height being covered with scroll on height?

Also, do we want to preserve original dialog box size after a msg has been expanded then collapsed back?
Original dialog:
image

Details expanded (what happens if msg has many more lines than this?):
image

After details collapsed:
image

**Comment by vabarbosa** [comment]
> I tested this locally and had some questions.
> I couldn't test anything where msg is super long, is max-height being covered with scroll on height?

yes, scroll bars should appear if the stack trace is bigger than the textarea/dialog size:

image



> 
> Also, do we want to preserve original dialog box size after a msg has been expanded then collapsed back?

this is the same behavior as in the original error dialog (i can investigate and see if it can easily be addressed)

**Comment by vabarbosa** [comment]
@karlaspuldaro i've made the change to restore dialog size after collapsing the stack trace section. thanks.

**Comment by marthacryan** [comment]
Just played around with it locally and it worked great.

**Comment by lresende** [comment]
@vabarbosa could you please rebase so I can merge it.

**Comment by vabarbosa** [comment]
> @vabarbosa could you please rebase so I can merge it.

@lresende this one should be all set now

**Pull request merged**
