### PR TITLE
Update clean-jupyterlab to Install Debugger and Xeus python on dev env

### PR DESCRIPTION
**Pull request by lresende**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
Waiting for https://github.com/jupyter-xeus/xeus-python/issues/308

**Comment by lresende** [comment]
@marthacryan @karlaspuldaro @ajbozarth 
Could a few of you give this a try and let me know if it works or if you see any issues? Seems ok for me now...

**Comment by karlaspuldaro** [comment]
It works for me :)
Just curious why debugger is being installed in clean-jupyterlab and not in Makefile?

**Comment by ajbozarth** [comment]
>Just curious why debugger is being installed in clean-jupyterlab and not in Makefile?

@karlaspuldaro I asked @lresende about that in a call a while back and the idea is this is kinda an early test. Debugger will be part of core in 3.0 so this would just be a stop gap until then for testing. Also even if it wasn't going into core, we didn't want it to be "part of" elyra like git and toc, but something we as a dev team make sure we support for customers that want to use it

**Comment by ajbozarth** [comment]
@lresende out of curiosity are we planning on extending debugger support to our python editor? (eventually)

**Comment by lresende** [comment]
I believe we tested and it was working via console integration, but the idea is to look into more deep integration.

**Pull request merged**
