### PR TITLE
Save as code snippet from editor selection

### LINKED ISSUE #1005: Save code snippet from editor selection
A user should be able to save a new code snippet by selecting a piece of code from either a file editor or a notebook cell.
This command can be added in the context menu (select text in editor --> right click)

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Resolves #1005

This PR implements the 'Save as Code Snippet' command.

1. Select text from notebook or file editor
2. Right click to open the context menu
3. Select 'Save as Code Snippet'
4. Metadata editor opens, code field is pre-populated with selection
5. User fills out remaining form fields

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Awesome. Please tag me when the feature is ready for a test drive!

**Review by ptitzler — APPROVED** [review]
LGTM. Tested different file types and various editors. One observation:  it appears that the action is only enabled for "cells" that are in edit mode. For example, open a notebook with a rendered markdown cell, and select some text. The save option is disabled. Is this intentional?

**Comment by marthacryan** [comment]
Just tried locally and it worked well! +1 on Patrick's comment about not needing the cells to be in edit mode. Also, not sure if this is the desired behavior, but I think it could be good to add the behavior of saving an entire cell as a snippet if none of the text is selected.

**Review by lresende — APPROVED** [review]

**Comment by karlaspuldaro** [comment]
@ptitzler @marthacryan Thank you for your feedback. 
I just pushed a commit addressing the selection of a rendered notebook cell and markdown preview.
I will create a follow up issue to add notebook cells as new snippet.

**Review by marthacryan — APPROVED** [review]

**Pull request merged**
