### PR TITLE
Refactor script processors, include brief detail on generic errors

### LINKED ISSUE #1337: Missing kernelspec on new notebooks created in VSCode
**Describe the issue**
Notebooks created in VSCode don't have a kernel spec until you run them, which causes issues when trying to run them with Elyra.

**To Reproduce**
1. Create and open an `.ipynb` file in VSCode
2. Add some content to it
3. Save the notebook file
4. Open the notebook Jupyter Lab
5. Add the notebook to an Elyra Pipeline
6. Set a runtime image for the node
7. Submit notebook for local execution
8. Get error `KeyError: 'kernelspec'`

**Screenshots or log output**
Screen Shot 2021-02-25 at 10 38 17 AM

**Expected behavior**
Either a better error message with steps to resolve the issue, or just magically run somehow.
(This can be fixed by opening the notebook in Jupyter Lab and re-saving the file or by running the notebook at least once in VSCode)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 1.5.3
 - Operating system: macos
 - Installation source: from source
 - Deployment type: local installation

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Local execution

**Notebook source:**
```
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": 3
  },
  "orig_nbformat": 2
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"hello world\")"
   ]
  }
 ]
}
```

### PR DESCRIPTION
**Pull request by kevin-bates**
Although this change was instigated by #1337, it primarily focuses on the aftermath of the merges for #1411 and #1418 - which essentially crossed paths, leaving the R script processor behind the Python script processor in terms of its error handling.  

While looking into #1337, it was found that Papermill release 2.3.3 handles the missing kernelspec much more gracefully than raising a `KeyError`.  Instead, it raises a `ValueError` indicating the kernel could not be determined nor was one provided.  However, the general error processing for notebook and both forms of script operations drop any level of details due to the unknown nature of error messages.  

This PR does the following:
- It introduces a new base class named `ScriptOperationProcessor` from which the _existing_`PythonScriptOperationProcessor` and `RScriptOperationProcessor` classes now derive.  This base class contains 90% of the applicable code with the subclasses providing their name and argument vectors.
- It introduces a `log_and_raise()` method on the base `FIleOperationProcessor` class that is available to all file-based operations.  Building on the work done in #1411, this method checks the length of the error message and truncates it to around the max (80), replacing overflow with an ellipses (...).
- Adds a test that removes the kernel metadata from a notebook node and ensures the appropriate error is raised.

When the kernelspec information is missing, the following message will be produced:
Screen Shot 2021-03-25 at 2 35 42 PM

Resolves #1337
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by lresende — APPROVED** [review]

**Comment by lresende** [comment]
Should we really truncate messages? I would say that the current issues we see on the dialog box limitation might not be present on different UIs? and if we truncate the message it would not be available for UIs that have the proper way to display them? Also, if it's only in the logs, what happens with managed environments such as Hub/Binder that does not expose the logs to the user?

**Review by lresende — CHANGES_REQUESTED** [review]
Changing to requested changes to discuss the direction of truncating error messages on the server-side versus on the UI.

**Comment by kevin-bates** [comment]
We can open up the message, it wasn't there prior to this, so I thought I'd add a length to it.  My concern is that we can easily get back to situations described [here](https://github.com/elyra-ai/elyra/issues/1467#issue-838948082) where some exception decides to be more verbose about things. 

> Also, if it's only in the logs, what happens with managed environments such as Hub/Binder that does not expose the logs to the user?

The details twisty thing essentially contains the portion of the "logs" for a user to send to an admin.

**Comment by kevin-bates** [comment]
Drilling down in this comment:
> what happens with managed environments such as Hub/Binder that does not expose the logs to the user?

I'm curious what you're getting at here?  In my opinion, exposing access to a server's log - whether that be directly or via some propagation mechanism using third-party software like Grafana - is the responsibility of the administrator/installation.  We don't even instruct users to redirect the server's console output to a file where the "logs" can be persisted and "exposed".  

Even if the logs were exposed to the users, are we expecting users to decipher what's going on - especially in error situations?  

Are you proposing we capture things like status information during a given request so that that information can be returned to the user, or that we expose logs via some kind of service to work around the scenario where logs are intentionally not made available to the end-user?

I'm just trying to understand the end-goal here because we'll need to design/conform our logging differently (and perhaps add state management altogether).

One thought would be to assign every request a, well, _request ID_, that is randomly generated at the start of each request.  The request ID would be logged on entry and exit from the handlers and potentially at _interesting data points_ and certainly be included in [`log_pipeline_info()`](https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor.py#L166) along with logged exceptions.  It would also be included _on_ the error dialog.  Then the user would simply reference the _request id_ as the "handle" that an administrator could use to decipher that particular request.  This is tantamount to a _session id_ associated with each request.

**Comment by kevin-bates** [comment]
After a sidebar (scrum), it was determined that having the traceback in the error details is sufficient _log information_ and inclusion of state or progress is not necessary.

We also discussed possibly moving the truncation to the client since other client interfaces may be able to handle the more unwieldy messages better.  We decided, for now, to continue with the truncation on the server after confirming that the full (non-truncated) message is available in the traceback.  Here's a screenshot, in which I temporarily shorted the max message length from 80 to 40 characters, showing that the full message is indeed in the traceback:
Screen Shot 2021-03-26 at 9 36 52 AM

Again, note that this truncation only happens for _general_  exceptions. We explicitly handle `PapermillExceutionError` (for notebooks) and `CalledProcessError` (for scripts) exceptions and they do not apply to this discussion.

SInce it sounds like the discussion is complete, I'm removing this from DRAFT.

**Review by kiersten-stokes — APPROVED** [review]
Looks great!

**Review by lresende — APPROVED** [review]

**Pull request merged**
