### PR TITLE
Remove Material UI ThemeProvider and Metadata header

### LINKED ISSUE #2948: Look into removing material ui packages
Users running in hosted environments with slower network latencies are experiencing Elyra startup delays that may be due to the lack of material ui packaging optimization.  We should understand where these costs are occurring and only packaging what is absolutely necessary for the proper functioning of Elyra.

### LINKED ISSUE #2951: Migrate off material UI in the Theme Provider
**Is your feature request related to a problem? Please describe.**
See https://github.com/elyra-ai/elyra/issues/2948 for context. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

### LINKED ISSUE #2952: Migrate off material UI in the Metadata Header UI
**Is your feature request related to a problem? Please describe.**
See https://github.com/elyra-ai/elyra/issues/2948 for context.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #2951 - removes the use of ThemeProvider and other material UI components to remove material UI from imports. 

Mostly maintains the same UI, but the main change is that it now uses the built-in context menu's from JupyterLab for the metadata header:
image

Fixes #2948
Fixes #2952

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
on a quick check there are a few things not changing when using dark mode:

category name & arrow icon:
Screen Shot 2022-10-06 at 12 47 52 PM

icons for arrange buttons:
Screen Shot 2022-10-06 at 12 48 13 PM

There also some issues in the metadata header but we're replacing that so no work needed there

**Comment by marthacryan** [comment]
@ajbozarth Thanks for catching those - I fixed the color of the palette categories but I checked and the icon colors are unrelated to my changes and if I'm remembering correctly, we did look into them and it was a canvas issue. We could make a separate issue for that but it's not actually straightforward to fix.

**Comment by ajbozarth** [comment]
I've push some updates including:
- I fixed the icon coloring I mentioned above (overrode it with css )
Screen Shot 2022-10-06 at 5 56 14 PM
Screen Shot 2022-10-06 at 5 56 18 PM
- I tinkered with the css classes on the header buttons, previously the context menu was added for both buttons so if you right clicked either the add or refresh it showed the add menu, I made it only show on the add button.
Screen Shot 2022-10-06 at 6 04 52 PM
- I removed the final Material UI dependency from pipeline editor by replacing the SnackBar Alert with a ToastContainer provided by https://github.com/fkhadra/react-toastify (the library core will be using in 4.0)
Screen Shot 2022-10-06 at 6 07 45 PM
   - Some change in toast functionality: 
       - clicking outside the notification no longer clears it (this is not natively supported by toastify, but if it's an issue we can write our own handler to do it)
       - multiple toast notification stack rather than replace the current one

**Review by ajbozarth — APPROVED** [review]
@marthacryan aside from the minor fixed I added, your code changes look solid and the UX is great when run locally

**Review by ptitzler — APPROVED** [review]
LGTM!

**Pull request merged**
