### PR TITLE
Support KFP with LDAP Dex auth

### PR DESCRIPTION
**Pull request by thesuperzapper**
### What changes were proposed in this pull request?
This PR resolves https://github.com/elyra-ai/elyra/issues/2210
- support `LDAP` Dex authentication for KFP
- if both `LDAP` and `staticPasswords` authentication are enabled, we use `staticPasswords`

### How was this pull request tested?

This PR was tested locally in the following configurations:
- `staticPasswords` enabled only
- `LDAP` enabled only
- `staticPasswords` and `LDAP` enabled

 ---

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@kiersten-stokes @lresende I think I have resolved the issues raised by @ptitzler.

The issue was that I assumed if `/auth/local/login` was not present in the URL that `/auth/local` wasn't either, (but in older dex versions this is not true), so the old code would rewrite to `/auth/local/local` (which is invalid). 

I believe I have fixed it now.

**Comment by thesuperzapper** [comment]
@akchinSTC I was using the [official dex example for LDAP](https://github.com/dexidp/dex/tree/master/examples/ldap) (with `docker-compose` to run the OpenLDAP server).

For now, you will have to install your own Kubeflow (however you're currently doing that), and then update your dex config to include [the example provider](https://github.com/dexidp/dex/blob/a15cd8788f0dd065ed5fa5f7e96696970852eac3/examples/ldap/config-ldap.yaml#L9-L47).

For the near future, I am actually building helm charts for Kubeflow, which will make all of this much easier to run manually (and probably automate inside Elyra tests).

**Comment by thesuperzapper** [comment]
@ptitzler @akchinSTC @kiersten-stokes the PR should (hopefully) be ready to merge now.

I have also included fixes for the template issues (urllib import, and user/pass argument extraction) raised in https://github.com/elyra-ai/elyra/pull/2212#discussion_r726591721.

**Comment by thesuperzapper** [comment]
@akchinSTC what specifically is blocking this, it definitely resolves the issue with LDAP issue?

In my mind, the idea to add more information to the logs (https://github.com/elyra-ai/elyra/pull/2212#discussion_r730093282) is unnecessary, especially as we will be changing this quite a bit as we add support for many more authentication types:
- https://github.com/elyra-ai/elyra/issues/2107

That is, we will need to improve per-auth-type logging as we resolve https://github.com/elyra-ai/elyra/issues/2107, but for now, we only support "Dex LDAP" or "Dex staticPasswords" (defaulting to "Dex staticPasswords" if both are enabled).

**Comment by akchinSTC** [comment]
> @akchinSTC just set `enablePasswordDB: false`

Thanks !
Had to comment out the `staticPasswords` fields as well but got past the issue once I did. Added the LDAP sample users to the `kubeflow-user-example-com` and works as expected.

**Pull request merged**
