### PR TITLE
Add R kernel installation to clean script

### PR DESCRIPTION
**Pull request by karlaspuldaro**
### What changes were proposed in this pull request?
This PR
- Adds install/uninstall commands to `clean-jupyterlab.sh` script for the packages 
`r r-essentials r-irkernel r-languageserver`, in order to help dev environment setup
- Updates documentation for r script support and dev workflow

### How was this pull request tested?
Manual testing:
- Run `clean-jupyterlab.sh` script, make sure R kernel is installed and listed in the logs.
- Open R editor + notebook and make sure R kernel  and R language server are available.
- Execute R scripts from notebook and R editor.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by ajbozarth — APPROVED** [review]
code lgtm, didn't try it locally because I have other code running though

**Comment by lresende** [comment]
Not sure if this was an env issue or not, but could you double-check if after running the clean-jupyterlab script you can run scripts in the script editor (R scripts or Python scripts)

**Comment by lresende** [comment]
You will need to install `r r-essentials r-irkernel` to have a `working` env, otherwise, there is very little you can do. Also, in this case, shouldn't we also install the lsp package for R as well?

**Review by lresende — CHANGES_REQUESTED** [review]
See above comments.

**Comment by karlaspuldaro** [comment]
@lresende Yes I was able to follow the testing steps in the PR description, including running scripts.  I noticed the first script run sometimes takes a bit longer than usual.
I'll add the extra dependencies and compare the performance.

**Review by lresende — APPROVED** [review]

**Comment by lresende** [comment]
It all works great now, thank you @karlaspuldaro

**Pull request merged**
