### PR TITLE
Fix ignored pipeline integration tests

### LINKED ISSUE #1596: Pipeline tests are failing after new pipeline-editor component
**Describe the issue**
It seems that a few css classifiers have changed the name and/or patterns with the merge of the new pipeline editor and the pipeline tests needs to be updated

### PR DESCRIPTION
**Pull request by lresende**
Fixes #1596 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by marthacryan — APPROVED** [review]
LGTM

**Review by marthacryan — CHANGES_REQUESTED** [review]
Sorry just saw the failing tests, going to take a look

**Review by bourdakos1 — APPROVED** [review]

**Review by bourdakos1 — CHANGES_REQUESTED** [review]
oh also didn't realize the failing tests, will look into it

**Comment by lresende** [comment]
Fixed by parallel pr from @bourdakos1

**Pull request closed without merging**
