### PR TITLE
Derive elyra from ExtensionApp

### LINKED ISSUE #1857: Improve server configurability
**Describe the issue**
As noted in the second paragraph of this https://github.com/elyra-ai/elyra/pull/1846#issuecomment-870979724, the server classes deriving from `Configurable` are not _flowing_ the necessary application class to enable their configurable attributes to be configured.  While some classes were addressed in #1846, this issue outlines what should be required to enable these attributes to be more easily configured.

The changes implemented in #1846 allow for the configuration of attributes of properly instantiated classes to be added to the `jupyter_server_config.py` file using a format of `c.{ConfigurableClass}.{ConfigurableAttribute} = value`.  However, if we convert our server extension registration from the older form of implementing [`_load_jupyter_server_extension()`](https://github.com/elyra-ai/elyra/blob/71ffc4783e140a91aa6f66d51f80138265c98acc/elyra/__init__.py#L41) to the more current approach of deriving from [`ExtensionApp`](https://github.com/jupyter-server/jupyter_server/blob/259571620cdc5ca62b4fbdcb0754d8d22d1b1f8e/jupyter_server/extension/application.py#L132) then we could allow users to add Elyra-specific configuration to the file `jupyter_elyra_config.py`.

Besides being the more modern approach, deriving from `ExtensionApp` also introduces the ability to invoke elyra as `jupyter elyra` - although I'm not sure if this will produce the desired results relative to our dependence on Jupyter Lab, it might (we'll have to see).

Once we're based on `ExtensionApp`, then we can flow _that_ application across our Configurable subclasses and enable the configuration of their attributes via the elyra-specific file.

Here are the current set of Configurable classes (as of this moment):
```
./pipeline/registry.py:148:class ComponentParser(SingletonConfigurable)
./pipeline/registry.py:631:class ComponentReader(SingletonConfigurable)
./pipeline/registry.py:686:class ComponentRegistry(SingletonConfigurable)
./pipeline/processor.py:37:class PipelineProcessorRegistry(SingletonConfigurable)
./pipeline/processor.py:57:class PipelineProcessorManager(SingletonConfigurable)
./pipeline/processor.py:149:class PipelineProcessor(LoggingConfigurable)
./pipeline/parser.py:28:class PipelineParser(LoggingConfigurable)
./contents/parser.py:30:class FileReader(LoggingConfigurable)
./contents/parser.py:145:class ContentParser(LoggingConfigurable)
./util/git.py:23:class GithubClient(LoggingConfigurable)
./util/cos.py:23:class CosClient(LoggingConfigurable)
./metadata/storage.py:69:class FileMetadataCache(SingletonConfigurable)
./metadata/manager.py:32:class MetadataManager(LoggingConfigurable)
./metadata/schema.py:31:class SchemaManager(SingletonConfigurable)
```
each of which (as well as any additions) will need to be checked that their `parent` attribute is conveyed during their instantiation.

### PR DESCRIPTION
**Pull request by kevin-bates**
As noted in https://github.com/elyra-ai/elyra/issues/1857#issue-935083837 there are a number of benefits to be gained by deriving the Elyra server extension from `ExtensionApp`.  This PR makes that change and addresses the configurability of all existing configurable subclasses by ensuring the parent application ('elyra') is appropriately conveyed in their instantiations.

With these changes, and taking the recently added file storage cache as an example, one can do the following...

- Launch Elyra using `jupyter-elyra ...` or `jupyter elyra ...` (note that the previous command of `jupyter lab` still works)
- Add Elyra-specific configurable traits on the command line: `jupyter elyra --FileMetadataCache.enabled = False`
- Configuration settings are honored from within a `jupyter_elyra_config.py` file (CLI options will override).  This file can be produced using `jupyter elyra --generate-config` (with all options, and their default values, commented out)
- Determine the version of Elyra via `jupyter elyra --version`
- Can see configurable options via `jupyter elyra --help-all`

<details>
<summary>jupyter elyra --help-all</summary>
<p>

```
Elyra Server

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
-y
    Answer yes to any questions instead of prompting.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.

Class parameters
----------------

Parameters are set from command-line arguments of the form:
`--Class.trait=value`. This line is evaluated in Python, so simple expressions
are allowed, e.g.:: `--C.a='range(3)'` For setting C.a=[0,1,2].

ElyraApp options
----------------
--ElyraApp.answer_yes=<Bool>
    Default: False
    Answer yes to any prompts.
--ElyraApp.config_file=<Unicode>
    Default: ''
    Full path of a config file.
--ElyraApp.config_file_name=<Unicode>
    Default: ''
    Specify a config file to load.
--ElyraApp.default_url=<Unicode>
    Default: ''
--ElyraApp.generate_config=<Bool>
    Default: False
    Generate default config file.
--ElyraApp.handlers=<List>
    Default: []
    Handlers appended to the server.
--ElyraApp.jinja2_options=<Dict>
    Default: {}
    Options to pass to the jinja2 environment for this
--ElyraApp.log_datefmt=<Unicode>
    Default: '%Y-%m-%d %H:%M:%S'
    The date format used by logging formatters for %(asctime)s
--ElyraApp.log_format=<Unicode>
    Default: '[%(name)s]%(highlevel)s %(message)s'
    The Logging format template
--ElyraApp.log_level=<Enum>
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--ElyraApp.open_browser=<Bool>
    Default: False
    Whether to open in a browser after starting. The specific browser used is
    platform dependent and determined by the python standard library
    `webbrowser` module, unless it is overridden using the --browser
    (ServerApp.browser) configuration option.
--ElyraApp.settings=<Dict>
    Default: {}
    Settings that will passed to the server.
--ElyraApp.static_paths=<List>
    Default: []
    paths to search for serving static files.
    This allows adding javascript/css to be available from the notebook server
    machine, or overriding individual files in the IPython
--ElyraApp.static_url_prefix=<Unicode>
    Default: ''
    Url where the static assets for the extension are served.
--ElyraApp.template_paths=<List>
    Default: []
    Paths to search for serving jinja templates.
    Can be used to override templates from notebook.templates.

FileMetadataCache options
-------------------------
--FileMetadataCache.enabled=<Bool>
    Default: True
    Caching is enabled (True) or disabled (False).
--FileMetadataCache.max_size=<Int>
    Default: 128
    The maximum number of entries allowed in the cache.

MetadataManager options
-----------------------
--MetadataManager.metadata_store_class=<Type>
    Default: 'elyra.metadata.storage.FileMetadataStore'
    The metadata store class.  This is configurable to allow subclassing of the
    MetadataStore for customized behavior.

PipelineProcessor options
-------------------------
--PipelineProcessor.enable_pipeline_info=<Bool>
    Default: True
    Produces formatted logging of informational messages with durations
    (default=True). (ELYRA_ENABLE_PIPELINE_INFO env var)
```
</p>
</details>

Resolves #1857
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
Not sure if related to the changes related to becoming an "Elyra app" or related to the removal of old jupyter_notebook_config.d json files but this regressed on Binder and possible JupyterHub (see #1474)

image

**Comment by kevin-bates** [comment]
Yeah, that looks like it might be the case - which is really a drag.  I've restored the `jupyter_notebook_config.d` directory, but I'm not sure we'll be out of the woods with that since `ExtensionApp` is entirely `jupyter_server` related.  (sigh)

**Comment by kevin-bates** [comment]
@lresende - I found that I also needed to restore the `jupyter_notebook_config.d` directory's entry in `setup.py` as part of my previous attempt to get Binder working - otherwise those files were not actually installed.  Once in place, Binder appropriately starts Elyra:
image

**Review by lresende — APPROVED** [review]
Tested with binder after the latest changes and it now seems to be working properly.

**Pull request merged**
