### PR TITLE
Uncap jinja2 and nbconvert dependency version

### LINKED ISSUE #1959: Install elyra-pipeline-editor-extension without downgrading jupyterlab-git and nbconvert?
**Describe the issue**

I tried to install `elyra-pipeline-editor-extension` from PyPI in my environment, already having `jupyterlab-git` in version 0.31 installed, nbconvert `6.0.7`, and `jinja2` 3.x, however `elyra-server` seems to have pinned requirements resulting in downgrade of those packages. The downgrade of `jupyterlab-git` and `nbconvert` is an inconvenience. I can imagine that `nbconvert` might be used somewhere, but is `jupyterlab-git` needed for pipeline-editor alone (maybe it is, I don't know)?

**To Reproduce**

```
pip install -U jupyterlab-git
pip install elyra-pipeline-editor-extension
```

See the latter downgrade git extension.

**Expected behavior**
I would like to be able to use the latest version of `jupyterlab-git` always. It would be perfect if the recent `nbcovert` would be supported too.

**Deployment information**
 - Elyra version: 2.2.4
 - Operating system: Ubuntu
 - Installation source: PyPI
 - Deployment type: local installation

PS. heads up: planning to cut a new release of LSP this week.

### PR DESCRIPTION
**Pull request by ajbozarth**
Fixes #1959 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kevin-bates** [comment]
These changes look fine.  However, if the intention of this is to resolve #1959, the [`Jinja2` dependency](https://github.com/elyra-ai/elyra/blob/3ac7544c95eaf172a8c86f87e3234acf8253070b/setup.py#L69) needs to be relaxed as well.  Does anyone know why that is capped?

@akchinSTC, @lresende

**Comment by ajbozarth** [comment]
> the Jinja2 dependency needs to be relaxed 

I missed that part of the issue, I'll relax that and test it, afaik there was no real reason to have it since 3.0 wasn't even released yet when that cap was added

**Comment by kevin-bates** [comment]
Looks like an [unrelated commit](https://github.com/elyra-ai/elyra/pull/1971/commits/3ac7544c95eaf172a8c86f87e3234acf8253070b) snuck in here.  Is that intentional?

Otherwise, I'm approving this PR - thanks @ajbozarth.

**Review by kevin-bates — APPROVED** [review]

**Comment by ajbozarth** [comment]
> Looks like an unrelated commit snuck in here. Is that intentional?

No, fixed via a merge with master

**Comment by ajbozarth** [comment]
Moved error handling fix into separate PR https://github.com/elyra-ai/elyra/pull/1984/files

**Review by lresende — APPROVED** [review]

**Pull request merged**
