### PR TITLE
Fix generic component schema to unblock frontend changes to file browse feature

### PR DESCRIPTION
**Pull request by kiersten-stokes**
This PR contains small changes to support https://github.com/elyra-ai/pipeline-editor/pull/208. 

Signed-off-by: Kiersten Stokes <kierstenstokes@gmail.com>

### What changes were proposed in this pull request?
Change the generic component schema for file-based arrays (file dependencies and outputs) to the new format that the frontend is expecting.

Code sandbox to be added by @marthacryan 

### How was this pull request tested?
Tests passing

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
Just pushed an update to use the rc with all the pipeline changes, once we confirm CI passes this should be good to merge (we may need to update the CI tests though)

**Comment by marthacryan** [comment]
Updates include 
* markdown in comments
* In file arrays, switch to having the "browse" button be next to the "add" button instead of having a "browse" button for each entry in the array. Also makes the entries in the file array editable.

**Comment by ptitzler** [comment]
Markdown support in comments is looking good.

image

**Comment by ptitzler** [comment]
Missing component error message rendering is looking better.

image

**Comment by ptitzler** [comment]
Browse button is looking good. We probably shouldn't render it for output files though, because it might lead to confusion:

image

By definition output files are produced when the node is executed. It appears that one cannot actually select a file (the file picker dialog shows up but selections are ignored), so this is more of a cosmetic usability issue.

**Comment by ptitzler** [comment]
@kiersten-stokes thanks for pushing that last minute change!

**Pull request merged**
