### PR TITLE
update pip and conda install doc

### LINKED ISSUE #993: Document how to install only a subset of the Elyra extensions
Follow-up to https://github.com/elyra-ai/elyra/issues/974

### PR DESCRIPTION
**Pull request by ptitzler**
This PR
 - updates the installation instructions, adding details how some of the extensions can be installed separately
 - closes #993 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
@akchinSTC do we also have conda recipes for these?

**Review by lresende — APPROVED** [review]

**Comment by akchinSTC** [comment]
> @akchinSTC do we also have conda recipes for these?

We do not, ill get started on them.

**Review by kevin-bates — COMMENTED** [review]
How does the [`elyra-server`](https://pypi.org/project/elyra-server/) come into play here?  Should it be referenced as an option?

**Comment by ptitzler** [comment]
> We do not, ill get started on them.

Super. It was more of a general question to make sure I didn't miss anything in the doc update (: 

 Thanks => https://github.com/elyra-ai/elyra/issues/1014

**Comment by ptitzler** [comment]
I also updated the `conda` section based on Alan's input.

**Review by lresende — APPROVED** [review]

**Pull request merged**
