### PR TITLE
Single node pipeline dependencies should be an array

### LINKED ISSUE #2014: Dependencies not set as list for notebooks/scripts that are run as pipeline causes validation failure
**Describe the issue**
Dependencies aren't being evaluated properly on `Run as pipeline` from notebook or script (any runtime). I think the value of `dependencies` in the pipeline JSON is being treated as a list, but it is being sent as a string.

**To Reproduce**
1. Open a notebook or script
2. Click on `Run as pipeline`
3. Submit with `Include file dependencies` box checked (in log output below, the default value of `*.py` is what was entered as the value here)

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Error Message</summary>
<pre>
{
  "severity": 1,
  "source": "Elyra Pipeline Validation Service",
  "type": "invalidFilePath",
  "message": "Property has an invalid path to a file/dir or the file/dir does not exist",
  "data": {
    "nodeID": "17226d56-5b20-4c13-a660-5455c6272cd9",
    "nodeName": "basic.ipynb",
    "propertyName": "dependencies",
    "value": "/Users/kierstenstokes/repos/elyra/p"
  }
}
{
  "severity": 1,
  "source": "Elyra Pipeline Validation Service",
  "type": "invalidFilePath",
  "message": "Property has an invalid path to a file/dir or the file/dir does not exist",
  "data": {
    "nodeID": "17226d56-5b20-4c13-a660-5455c6272cd9",
    "nodeName": "basic.ipynb",
    "propertyName": "dependencies",
    "value": "/Users/kierstenstokes/repos/elyra/y"
  }
}
</pre>
</details>

<details><summary>Debug Log Output</summary>
<pre>
[D 2021-08-04 12:24:17.609 ServerApp] Pipeline SchedulerHandler now executing post request
[D 2021-08-04 12:24:17.609 ServerApp] JSON payload: {'doc_type': 'pipeline', 'version': '3.0', 'json_schema': 'http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json', 'id': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'primary_pipeline': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'pipelines': [{'id': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'nodes': [{'id': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'type': 'execution_node', 'op': 'execute-notebook-node', 'app_data': {'component_parameters': {'filename': 'examples/basic.ipynb', 'runtime_image': 'continuumio/anaconda3:2020.07', 'outputs': [], 'env_vars': [], 'dependencies': '*.py', 'include_subdirectories': False, 'cpu': '', 'gpu': '', 'memory': ''}, 'ui_data': {'label': 'basic.ipynb'}}}], 'app_data': {'name': 'basic', 'runtime': 'kfp', 'runtime-config': 'kfp_cloning', 'version': 4, 'ui_data': {'comments': []}, 'source': 'basic.ipynb'}}], 'schemas': []}
[D 2021-08-04 12:24:17.620 ServerApp] Validation checks completed. Results as follows: {'title': 'Elyra Pipeline Diagnostics', 'description': 'Issues discovered when parsing the pipeline', 'issues': [{'severity': 1, 'source': 'Elyra Pipeline Validation Service', 'type': 'invalidFilePath', 'message': 'Property has an invalid path to a file/dir or the file/dir does not exist', 'data': {'nodeID': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'nodeName': 'basic.ipynb', 'propertyName': 'dependencies', 'value': '/Users/kierstenstokes/repos/elyra/examples/p'}}, {'severity': 1, 'source': 'Elyra Pipeline Validation Service', 'type': 'invalidFilePath', 'message': 'Property has an invalid path to a file/dir or the file/dir does not exist', 'data': {'nodeID': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'nodeName': 'basic.ipynb', 'propertyName': 'dependencies', 'value': '/Users/kierstenstokes/repos/elyra/examples/y'}}]}
[W 2021-08-04 12:24:17.621 ServerApp] 400 POST /elyra/pipeline/schedule?1628097857604 (::1) 12.52ms referer=http://localhost:8888/lab/tree/examples/basic.ipynb</pre>
</details>

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.0.rc4

### PR DESCRIPTION
**Pull request by ajbozarth**
Fixes #2014 

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Confirmed. Standalone pipeline submission is successful, verified that dependency wildcard expansion is working (checked archive in minio) and no errors from the validation service.

**Review by bourdakos1 — APPROVED** [review]

**Comment by bourdakos1** [comment]
just a note, the cpu/gpu/memory are actually strings instead of numbers

**Comment by ajbozarth** [comment]
> just a note, the cpu/gpu/memory are actually strings instead of numbers

I would assume that similar to how the dependencies string was being ready as a string array of each character that this values were being read as the number contained in the string (and would error in some way if a user entered a non-number)

**Review by akchinSTC — APPROVED** [review]

**Comment by akchinSTC** [comment]
opened https://github.com/elyra-ai/elyra/issues/2016 to address follow up

**Pull request merged**
