### PR TITLE
Update to JupyterLab 3.3.0

### PR DESCRIPTION
**Pull request by akchinSTC**
### What changes were proposed in this pull request?

Updates Elyra to use JupyterLab 3.3.0
### How was this pull request tested?

Example pipelines (covid/noaa) were run without issues
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
Also, please make sure we resolve the warnings from the Browser console, which seems that some npm libraries need to be updated.

**Comment by akchinSTC** [comment]
> Also, please make sure we resolve the warnings from the Browser console, which seems that some npm libraries need to be updated.

Will take a look and update as necessary

**Comment by akchinSTC** [comment]
@lresende - let me know if you're still seeing warnings. I tried looking in the console in chrome but didn't see anything about outdated packages.

**Comment by lresende** [comment]
@akchinSTC the warnings are gone after a `clean-jupyterlab.sh`. Having said that, it looks like package.json still have a few references to `3.3.0-rc.0` dependencies.

```
 grep -ri 3.3.0-rc.0                                                                                                                                                     elyra/pr-2519
./yarn.lock:"@jupyterlab/apputils@^3.3.0", "@jupyterlab/apputils@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/cells@^3.3.0", "@jupyterlab/cells@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/codeeditor@^3.3.0", "@jupyterlab/codeeditor@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/codemirror@^3.3.0", "@jupyterlab/codemirror@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/docregistry@^3.3.0", "@jupyterlab/docregistry@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/nbformat@^3.3.0", "@jupyterlab/nbformat@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/notebook@^3.3.0", "@jupyterlab/notebook@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/rendermime@^3.3.0", "@jupyterlab/rendermime@^3.3.0-rc.0":
./yarn.lock:"@jupyterlab/testutils@3.3.0-rc.0":
./yarn.lock:  version "3.3.0-rc.0"
./yarn.lock:  resolved "https://registry.yarnpkg.com/@jupyterlab/testutils/-/testutils-3.3.0-rc.0.tgz#02370df702fad3408902c9edc5700159052a427a"
./yarn.lock:    "@jupyterlab/apputils" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/cells" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/codeeditor" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/codemirror" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/docregistry" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/nbformat" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/notebook" "^3.3.0-rc.0"
./yarn.lock:    "@jupyterlab/rendermime" "^3.3.0-rc.0"
./package.json:    "@jupyterlab/testutils": "3.3.0-rc.0",
```

**Review by lresende — CHANGES_REQUESTED** [review]
See previous comments for references to `3.3.0-rc.0`

**Review by lresende — APPROVED** [review]

**Pull request merged**
