### PR TITLE
Use legacy resolver during binder build

### LINKED ISSUE #1455: 2.1 Binder build never completes due to package dependency conflicts
**Describe the issue**
Open https://mybinder.org/v2/gh/elyra-ai/elyra/v2.1.0 and check the build log file

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1 + master
 - Installation source: binder

### PR DESCRIPTION
**Pull request by lresende**
Fixes #1455 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
The binder build completed but there appears to be a problem when JL comes up:

image

**Comment by lresende** [comment]
Current deployed :
```

jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.20.0
ipykernel        : 5.5.0
jupyter client   : 6.1.11
jupyter lab      : 3.0.11
nbconvert        : 5.6.1
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

    - Validating...
      jupyter_lsp 1.1.4 OK
    - Validating...
      jupyter_resource_usage  OK
    - Validating...
      jupyterlab 3.0.11 OK
    - Validating...
      nbdime 3.0.0.b1 OK
    - Validating...
      nteract_on_jupyter 2.1.3 OK
    - Validating...
      jupyter_offlinenotebook  OK
config dir: /srv/conda/envs/notebook/etc/jupyter
    jupyter_lsp  enabled
    jupyter_resource_usage  enabled
    jupyterlab  enabled
    nbdime  enabled
    nteract_on_jupyter  enabled
    jupyter_offlinenotebook  enabled

Config dir: /home/jovyan/.jupyter

Config dir: /srv/conda/envs/notebook/etc/jupyter
    elyra enabled
    - Validating elyra...
      elyra 2.2.0.dev0 OK
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.1.4 OK
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage  OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.11 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.30.0b1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    nbdime enabled
    - Validating nbdime...
      nbdime 3.0.0.b1 OK
    jupyter_offlinenotebook enabled
    - Validating jupyter_offlinenotebook...
      jupyter_offlinenotebook  OK

Config dir: /usr/local/etc/jupyter


JupyterLab v3.0.11
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.5.0 enabled OK (python, jupyter-resource-usage)
        @krassowski/jupyterlab-lsp v3.4.1 enabled OK (python, jupyterlab_lsp)
        @jupyterlab/git v0.30.0-beta.1 enabled OK (python, jupyterlab-git)

Other labextensions (built into JupyterLab)
   app dir: /srv/conda/envs/notebook/share/jupyter/lab
        @elyra/code-snippet-extension v2.2.0-dev enabled OK
        @elyra/metadata-extension v2.2.0-dev enabled OK
        @elyra/pipeline-editor-extension v2.2.0-dev enabled OK
        @elyra/python-editor-extension v2.2.0-dev enabled OK
        @elyra/theme-extension v2.2.0-dev enabled OK
        nbdime-jupyterlab v2.1.0-beta.1 enabled OK


   linked packages:
        @elyra/metadata-common: /home/jovyan/packages/metadata-common
        @elyra/services: /home/jovyan/packages/services
        @elyra/ui-components: /home/jovyan/packages/ui-components

Disabled extensions:
    @jupyterlab/launcher-extension (all plugins)
```

**Review by akchinSTC — APPROVED** [review]
LGTM

**Comment by lresende** [comment]
This fixes the build issue, and the extension registration issue is resolved in #1476

**Review by kevin-bates — APPROVED** [review]
LGTM - thanks for dealing with this.

**Pull request merged**
