### PR TITLE
Add offical logos for Python and R

### LINKED ISSUE #1445: Update icons used for Python and R
We should update the icons to use official logos for Python and R.

### PR DESCRIPTION
**Pull request by ajbozarth**
Currently we use the jupyterlab python logo, but with the addition
of R support we would like to have pipelines use the the offical
logos for each node instead of ones designed for the lab file browser

Fixes #1445

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
Leaving this WIP for a few reasons

1. need to test/update it once #1418 is merged
2. I'm not sure yet on if I've changed the logo everywhere it should be changed

Places to change the python logo and whether I've changed them:

- In the file browser. I have NOT changed this, but am unsure if we should
- In the launcher. I have changed this, but am unsure if we should
- In the tab bar for python editor. I have NOT changed this, but it should match the file browser no matter our choice.
- In pipelines. I changed this and it should use the new icon.

**Comment by bourdakos1** [comment]
I think we should leave the `file browser` and `tab bar` as is and have the pipeline nodes match that.

For the `launcher` icons, I think we should do our best to match the other present launcher icons. I updated the "official" svg to match the other pngs more closely: https://codesandbox.io/s/python-logo-z05p4?file=/src/App.tsx

I personally think the icon in this PR is awkwardly too close to the other launcher icons, but not close enough so it draws your eye in a bad way. If we don't use something closer to the pngs, then I think we should go back to using the icon from `file browser`

**Comment by ajbozarth** [comment]
I've pushed a few updates:

- Updated the R icon in pipelines
- Updated to use Python icons in all four use cases listed in my previous comment.
   - The code for changing the icon in the file browser won't work until https://github.com/jupyterlab/jupyterlab/pull/9958 is merged

Some screenshots of the current state:
Screen Shot 2021-03-18 at 1 46 35 PM
Screen Shot 2021-03-18 at 1 46 58 PM
Screen Shot 2021-03-18 at 1 47 15 PM

**Comment by ajbozarth** [comment]
The upstream PR has been merged and I've pushed an update here to support both python and r icon in the side bar, new screenshots:

Screen Shot 2021-03-22 at 1 22 19 PM
Screen Shot 2021-03-22 at 1 22 51 PM
Screen Shot 2021-03-22 at 1 22 58 PM

**Comment by lresende** [comment]
The related lab PR https://github.com/jupyterlab/jupyterlab/pull/9958 is now available on `JupyterLab 3.0.12`. Also, on existing pipelines, as the node icon is part of the pipeline, you would need to re-add the node to the pipeline.

**Comment by ajbozarth** [comment]
> Also, on existing pipelines, as the node icon is part of the pipeline, you would need to re-add the node to the pipeline.

It may be worth including updating the icon as a pipeline version update

**Comment by lresende** [comment]
LGTM:

image

**Pull request merged**
