### PR TITLE
Cleanup Pipeline Editor integration tests

### PR DESCRIPTION
**Pull request by lresende**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by marthacryan** [comment]
**Note**: My last two commits add an extra line `getFileByName('helloworld.ipynb').click()` immediately before `getFileByName('helloworld.ipynb').rightclick()`, because for some reason, cypress' `rightclick` function does not select the element that it right clicks. The context menu appears, but the file browser element is not selected. Our code uses the selected elements in the file browser to determine what to add into the pipeline, so it breaks our code when the right click doesn't select the element in the browser. For now, adding the extra `click` call does the trick, but it might be good to consider whether we should change our code to make sure that we're using the element that was right clicked on somehow.

**Comment by lresende** [comment]
@marthacryan, that seemed to have resolved that issue, thank you.

**Review by marthacryan — APPROVED** [review]
LGTM

**Review by akchinSTC — APPROVED** [review]
LGTMT

**Pull request merged**
