### PR TITLE
Update github workflows to use v3/v4 actions

### PR DESCRIPTION
**Pull request by akchinSTC**
Signed-off-by: Alan Chin <akchin@us.ibm.com>

Outdated workflow actions are triggering deprecation warnings in our github action CI results

image

image

### What changes were proposed in this pull request?
 - Use newer versions of outdated github actions
 - Adjust scheduled build job start time - recent builds were canceled  because they didn't finish within the 6 hours time limit, e.g. https://github.com/elyra-ai/elyra/actions/runs/4034820821 

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Additional changes are required in https://github.com/akchinSTC/elyra/blob/update-workflow-v3/.github/workflows/codeql-analysis.yml

image

**Comment by kevin-bates** [comment]
@akchinSTC - does this provide any benefit other than being on the latest action versions? I'm just curious about what the impetus was for this.

**Review by ptitzler — APPROVED** [review]
LGTM! Confirmed that the github actions no longer trigger deprecation warnings.

**Comment by akchinSTC** [comment]
> @akchinSTC - does this provide any benefit other than being on the latest action versions? I'm just curious about what the impetus was for this.



> @akchinSTC - does this provide any benefit other than being on the latest action versions? I'm just curious about what the impetus was for this.

@kevin-bates - Updated the description with screenshots. In short, outdated actions were triggering deprecation warnings.

**Review by kevin-bates — APPROVED** [review]
Thanks @akchinSTC. I also like the cron update.

**Pull request merged**
