### PR TITLE
Fix resource values that require values > 0 from treating null as <= 0

### PR DESCRIPTION
**Pull request by bourdakos1**
fixes: #1412 

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by bourdakos1** [comment]
woops, how did this happen

**Comment by akchinSTC** [comment]
Built and tested on master. 
- setting saving cpu and memory at 0 or negative value, results in error 
- setting GPU at negative value, results in error, zero value allowed 
- Also removal of the value (setting to null in file) does not throw error. 
image
image

**Comment by lresende** [comment]
@bourdakos1 could you also take a look at [cleanNullProperties()](https://github.com/elyra-ai/elyra/blob/de5ffbf9f476127c45fd7bcaadab6bf11f44ac7b/packages/pipeline-editor/src/PipelineEditorWidget.tsx#L862) and if we need to do something similar to #1406. 

I know we are checking for nulls now, but I think nulls should never reach a saved and/or submitted pipeline.

**Comment by bourdakos1** [comment]
It looks like we only strip nulls when submitting/exporting not saving/validating

**Comment by lresende** [comment]
> It looks like we only strip nulls when submitting/exporting not saving/validating

Could we fix that as well?

**Comment by bourdakos1** [comment]
Is that an issue?

**Pull request merged**
