### PR TITLE
Refactor different runtimes into its own folder/module

### PR DESCRIPTION
**Pull request by lresende**
Refactor different runtimes into its own folder/module to better compartmentalize the runtime-specific code and serve as an example to others that are working on bringing your own runtime code. 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
@kiersten-stokes some tests are failing complaining an instance of `new_registry` already exists. Could you shed some light on why these tests are failing without much code change and just moving things around folders?

**Comment by kiersten-stokes** [comment]
@lresende Looks like it's just due to the location of some resources changing! I can push a commit for those in a few. 

Also, I think the location of a few of our url-based test resources that reference the repo might cause some failures on merge. I'll go through and try to find all the instances of those as well

**Comment by kiersten-stokes** [comment]
We should be good to go on the url-based resources since none that I found will be changing location

**Review by kiersten-stokes — APPROVED** [review]
LGTM!

**Comment by kevin-bates** [comment]
One of the issues that surfaced when we moved the kfp-notebook code under elyra/kfp was that the IDE (PyCharm) now gets confused about the import statements in code that references the KFP client package:

image
and I just have to ignore those errors.

Do you see any similar issues with having this subdirectory named `kfp`?

**Comment by lresende** [comment]
@kevin-bates it looks ok to me

image

**Comment by kevin-bates** [comment]
Should we hold off on this merge since I believe it will be easier to resolve conflicts after #2094 is merged rather than the other way around?

**Review by kevin-bates — COMMENTED** [review]
Could you please update the description for why this pull request is being created?  (I know it's related to serving as an example for what others might implement relative to bringing their own runtimes, but am not sure if there's anything else, and it deserves some explanation.)

**Comment by kevin-bates** [comment]
I probably have something messed up in my IDE, but here's another example.  The processor_kfp file wants to load kfp and ends up loading the kfp in our repo.  As a result, there's no Client module:
```
/opt/anaconda3/envs/elyra-dev/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 49628 --file /opt/anaconda3/envs/elyra-dev/bin/elyra-metadata install component-registries --display_name=abc --description "Load data from external data sources" --runtime=ttt --location_type=www --paths=ppp
Connected to pydev debugger (build 211.7628.24)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/processor_kfp.py", line 29, in <module>
    from kfp import Client as ArgoClient
ImportError: cannot import name 'Client' from 'kfp' (/Users/kbates/repos/oss/elyra-ai/elyra/elyra/kfp/__init__.py)
```
If I edit the IDE debug configuration to not add the source or content roots to PYTHONPATH, I get past this - but we want those enabled in other cases.  Just a heads up.  (I ran into this in EG for the docker process-proxy which is why its named docker_swarm.py instead of docker.py.)

**Comment by akchinSTC** [comment]
+1 
can merge this, doesn't conflict with changes in #1761

**Pull request merged**
