### PR TITLE
Sort palette nodes by component label

### LINKED ISSUE #2171: Consider sorting components in palette for consistent display
**Is your feature request related to a problem? Please describe.**
With threading now implemented to read and parse component definitions, the order in which the components are rendered may change depending on the order in which threads execute.

**Describe the solution you'd like**
Discussion is needed to determine where the sorting should be done. 

**Describe alternatives you've considered**
We can also consider just leaving it as-is as a visual for when components are updating.

### PR DESCRIPTION
**Pull request by kiersten-stokes**
Resolves #2171 (again)

After the merge of #2241, the component `op`s are no longer in alphabetical order according to the label (name) of the component. 

Note that `localeCompare` is already case insensitive.

### What changes were proposed in this pull request?
This PR gets the label from the palette nodes from the `app_data.ui_data.label` field. The top-level `label` field (not within `app_data.ui_data`) appears to be available on each node object, but when trying to directly access it directly, build fails with the following error: 

```
@elyra/pipeline-editor-extension: src/pipeline-hooks.ts(142,9): error TS2339: Property 'label' does not exist on type '{ op: string; id: string; type: "execution_node"; inputs: { app_data: any; }[]; outputs: { app_data: any; }[]; app_data: any; }'.
```

I **think** this might have something to do with Canvas and how they enforce attributes on a node? I'm guessing this is what @bourdakos1 was alluding to with his comment [here](https://github.com/elyra-ai/elyra/blob/5eceb1753e45801bfc356a91582d045cb551daf1/packages/pipeline-editor/src/pipeline-hooks.ts#L124).

All this to say, this PR seems to work, but I don't know if it's the best way to get it done. Will definitely need some input from the frontend experts.

### How was this pull request tested?
Tested manually to ensure that components are sorted by label.
 
Screen Shot 2021-11-04 at 5 37 47 PM

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by bourdakos1** [comment]
@kiersten-stokes I think we manually created the type definition, if there is a label at the top level we can update it and typescript will stop complaining

**Comment by bourdakos1** [comment]
I can push some changes to this tomorrow morning

**Comment by kiersten-stokes** [comment]
> @kiersten-stokes I think we manually created the type definition, if there is a label at the top level we can update it and typescript will stop complaining

Ah ok good, that's easier than I thought it would be! (well, for someone besides me, that is 😄). But yeah `label` is there at the top level when I checked out each object so we're good to go on that front

**Comment by bourdakos1** [comment]
pushed changes, but did not do any testing haha 🤞

**Comment by bourdakos1** [comment]
Tested, seems to be working

**Pull request merged**
