### PR TITLE
feat: allow users to use version suffix pipeline runs

### LINKED ISSUE #3182: Introduce pipeline version with numbers(v1,etc) instead of datastamp
**Is your feature request related to a problem? Please describe.**

Currently, when pipelines are created using elyra from the Notebooks, each additional iteration of the pipeline run, create a new pipeline version, the pipeline version names are defined in the following manner: <pipeline-name>+<datastamp>.

For users, when looking at the specific runs, it is hard to know directly which version is related to the run.

Screenshot from 2023-09-19 16-59-02

**Describe the solution you'd like**

For the users to have the pipeline version names defined with numbers instead of data stamps, might be convenient to interpret the run more accurately for each pipeline version run.  like <pipeline-name>+<number> example: test-v1

**Describe alternatives you've considered**

NA

**Additional context**

Related-issue: https://github.com/opendatahub-io/notebooks/issues/206

### PR DESCRIPTION
**Pull request by rkpattnaik780**
### What changes were proposed in this pull request?

Currently, when pipelines are created using elyra from the Notebooks, each additional iteration of the pipeline run creates a new pipeline version identified by timestamp.

The PR will allow user to switch from timestamp identifiers to versions numbers (v1, etc) using an environment variable `KFP_SUFFIX_USE_VERSION`. This will make the pipeline runs easily distinguishable.

Fixes #3182 

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
@rkpattnaik780 overall LGTM, but could you mention the new env var in the docs

**Comment by lresende** [comment]
@rkpattnaik780 could you also rebase the pr to make sure all the tests are passing

**Comment by rkpattnaik780** [comment]
In an off-thread discussion, we noticed the current implementation will fail if:

- once we have few pipeline. ex: 10 , latest version will be `-v10`
- a user delete the 6th pipeline, the total_size=9
- the next call of pipeline, would try to create the version '-v10`
again

We are trying to find a workaround for this issue. Cc @harshad16

**Comment by harshad16** [comment]
Thanks for the pull request @rkpattnaik780 
and for the review @lresende 
due this reason: https://github.com/elyra-ai/elyra/issues/3182#issuecomment-1756077849
we don't require the feature, we have closed the issue.
Please feel free to close the PR as well.

**Pull request closed without merging**
