### PR TITLE
New extension - Code Viewer

### PR DESCRIPTION
**Pull request by ajbozarth**
Adds a new Elyra extension: Code Viewer

Code Viewer adds a command that will display a given chunk of
code (string) in a transient read-only "editor" without needing to
create a file.

The new command takes in a string of the code chunk or text to
display as well as an option mime type or extension to enable code
highlighting. It then opens a read-only "editor" containing the given
content. This allows for transient display of text without the need to
persist it to a file to display it to a user.

Frontend for https://github.com/elyra-ai/elyra/issues/2549

Remaining To Do's:
- [x] Add support for extensions in addition to mime types
- [x] Remove temporary test code from pipeline editor

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Would it be possible to enable the `copy` [to clipboard] action on the context menu? 

image

**Comment by ajbozarth** [comment]
> Would it be possible to enable the copy [to clipboard] action on the context menu?

I actually checked and I need to work on the context menu in general. If you open a md file then switch to a viewer the open preview option shows up and opens the preview for the md tab that was just open

**Comment by ptitzler** [comment]
Since there isn't anything code specific about the viewer's functionality, should we perhaps change the extension name to something more generic? For example, one might use the viewer to display plain text.

**Comment by ptitzler** [comment]
I've created a new label `component:code-viewer` in this repo to allow for proper classification of follow-up work.

**Review by marthacryan — APPROVED** [review]
Code LGTM - haven't tested locally

**Comment by ajbozarth** [comment]
I "solved" the context menu issues by simply disabling the jupyterlab context menu and letting the normal system context menu open when inside the viewer. (This lets users copy text). 

I've also removed the test code so this is ready to merge. If further testing is desired you will want to check out the code then revert one commit to re-add the test code.

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
