### PR TITLE
Add elyra documentation link in elyra-metadata help

### LINKED ISSUE #2718: 'elyra-metadata' help should display a link to the documentation
**Is your feature request related to a problem? Please describe.**
The `elyra-pipeline` CLI displays a documentation link when help is invoked, e.g.
```
$ elyra-pipeline --help
Usage: elyra-pipeline [OPTIONS] COMMAND [ARGS]...

  Run Elyra pipelines in your local environment or submit them to an external
  service, such as Kubeflow Pipelines or Apache Airflow.

  Find more information at: https://elyra.readthedocs.io/en/latest/
```

The link is specific to the version of Elyra that is installed, e.g. `https://elyra.readthedocs.io/en/v3.8.0/` for version 3.8.

**Describe the solution you'd like**
It would be helpful if the `elyra-metadata` command would do the same. The current output is 
```
$ elyra-metadata --help

Manage Elyra metadata.

Subcommands
-----------
...

```

### PR DESCRIPTION
**Pull request by sgonsal**
### What changes were proposed in this pull request?
Add a link to Elyra documentation in elyra-metadata cli help.
Closes #2718 

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
In the `elyra-pipeline` app we've used a static approach that does not require an outbound HTTP call to determine which URL to use. In a nutshell the code only [includes the 'default' dev URL](https://github.com/elyra-ai/elyra/blob/master/elyra/cli/pipeline_app.py#L287), which is [automatically replaced with the appropriate version identifier when a new  Elyra release is created using the release script](https://github.com/elyra-ai/elyra/blob/master/create-release.py#L140-L144).

**Comment by sgonsal** [comment]
@ptitzler I see what you mean, Making the change to use a similar static approach.
Thanks :)

**Comment by ptitzler** [comment]
Super! Thank you. Your approach would have certainly worked, but might open a URL that is different from the one that is used when one opens the documentation link in the JupyterLab UI or runs the `elyra-pipeline` CLI command.

Could you modify your PR description to use one of the [github keywords](
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that will automatically close the issue when the PR gets merged?

**Review by akchinSTC — CHANGES_REQUESTED** [review]
Thanks for the improvements!

In the create release script, we update the version to the new version but we also then update it again here: https://github.com/elyra-ai/elyra/blob/c0ea9fcd683f47b3758edd94e19fe5b2cbaee26a/create-release.py#L226

to iterate into the next development version. Could you make the sed changes here as well?

**Pull request merged**
