### PR TITLE
Update screens and info on installation of KFP on Docker Desktop

### PR DESCRIPTION
**Pull request by akchinSTC**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
Don't we need to enabled `show system containers`?

**Comment by kevin-bates** [comment]
Why is showing system containers required? Are the containers launched as pipeline nodes considered system containers?

**Comment by lresende** [comment]
I believe this was one of the issues we identified while testing in our local scenario, unless I am mistaken, that's why I marked as `change requested` so we wait for @akchinSTC response from his testing.

**Comment by kevin-bates** [comment]
Ok - sounds good.  My understanding was that _show system containers_ merely populates `docker ps` with the gnarly system images.  I can't imagine how that checkbox would affect operations unless some code somewhere is actually performing a shell command to discover something.

**Comment by akchinSTC** [comment]
@lresende - show system containers is what @kevin-bates has noted. It merely allows the users to see the k8s cluster containers when using the docker commands. With that said, it may help with debugging if docker desktop has not made the context available yet and the k8s cluster is having issues starting. I propose adding another small section towards the end with this doc with this enabled to facilitate troubleshooting

**Pull request merged**
