### PR TITLE
Fix tooltip of launcher icons

### LINKED ISSUE #1674: Launcher/Pipeline button tool tips are incorrect for KFP/AA editors
**Describe the issue**

The _tool tips_ for the image (hover over image) and the button text (hover over the displayed text) should be the same for the image/text and properly reflect the pipeline type, e.g `Generic Pipeline Editor`, `Kubeflow Pipelines Pipeline Editor`, `Apache Airflow Pipeline Editor`

image

image

image

**To Reproduce**
1. On the Launcher page hover over the buttons in the Elyra category

**Expected behavior**

See above

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.3/master

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #1674. Text in the tooltip is the same regardless of where you're hovering in the launcher card. 
Screen Shot 2021-05-20 at 11 33 32 AM
image
Screen Shot 2021-05-20 at 11 33 42 AM

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by ptitzler — APPROVED** [review]
LGTM

**Review by ajbozarth — APPROVED** [review]
This LGTM, but @ptitzler I saw that the generic pipeline button says `Generic Pipeline Editor` whereas the others just say `Pipeline Editor` I figured this is because they have the runtime name in tier logo, but I feel like the generic should also just say `Pipeline Editor` and the have `Generic Pipeline Editor` in it's tool tip. The way it is now just looks off to me and I was informed you were the one who wanted it to say `Generic`

**Comment by ptitzler** [comment]
> The way it is now just looks off to me and I was informed you were the one who wanted it to say Generic

It does, but my thinking was that the "generic" logo is not something users are familiar with, nor does it include text. The other two logos include the names "Kubeflow" and "Apache Airflow", which provide context for "pipeline editor" -> e.g. "Kubeflow pipeline editor",  whereas "unknown symbol pipeline editor" does not. Would adding the text "Generic" to the icon make it better?

**Comment by ptitzler** [comment]
See also screen capture in https://github.com/elyra-ai/elyra/pull/1683#issue-649371699, which uses `"generic <pipeline symbol>"`

**Pull request merged**
