### PR TITLE
Remove dead code

### LINKED ISSUE #1741: Identify and remove duplicate code migrated to pipeline-editor project
**Describe the issue**
Looks like we are starting to have some duplicate code from when we started moving things to the pipeline-editor package.

Like migration code in [elyra/pipeline](https://github.com/elyra-ai/elyra/blob/abb5191c1c57e2f174069a1170c2f9568546b205/packages/pipeline-editor/src/PipelineService.tsx#L308) and [piepeline-editor](https://github.com/elyra-ai/pipeline-editor/blob/44bb3f6f033b00930229acbb0fe8a7cf793062a4/packages/pipeline-services/src/migration/index.ts#L23)

### PR DESCRIPTION
**Pull request by bourdakos1**
Fixes #1741

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by lresende — APPROVED** [review]

**Comment by ajbozarth** [comment]
So I've done some testing locally and we do still use the files in `node/`, because with those gone the refresh env vars button goes away. I edited those to add `canRefresh` when we added that feature.

**Comment by ajbozarth** [comment]
So I've done some testing locally and we do still use the files in `node/`, because with those gone the refresh env vars button goes away. I edited those to add `canRefresh` when we added that feature.

**Review by ajbozarth — CHANGES_REQUESTED** [review]
note above comment

**Comment by bourdakos1** [comment]
@ajbozarth I think this would need to change on the server side now, if you check master it is probably gone there too

**Review by ajbozarth — APPROVED** [review]
With the fix I opened in #1790 this is g2g

**Pull request merged**
