### PR TITLE
Fixes #1160 - Add metadata type to delete confirmation dialog message

### LINKED ISSUE #1160: Delete confirmation dialog message does not reveal metadata type
image

Not totally sure but I believe in earlier releases the message was more user friendly and said something like "`Delete [runtime configuration | runtime image | snippet | ...] : <id>`".

image

### PR DESCRIPTION
**Pull request by tlzhu19**
### What changes were proposed in this pull request?

Before fix:
Both messages said "Delete metadata", see https://github.com/elyra-ai/elyra/issues/1160

After fix:
Change to "Delete runtime image" and "Delete runtime configuration"
Screen Shot 2021-05-24 at 10 48 53 AM
Screen Shot 2021-05-24 at 10 48 28 AM

### How was this pull request tested?

Ran `jupyter lab --watch`, made the code changes and then verified the changes in the UI.

Fixes #1160
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
> `Delete XYZ: ...?`

Perhaps we should use the opportunity and change the text to `Delete XYZ 'xyz'?`, where `xyz` is the metadata instance name? As is, the wording with the `:` is a bit odd for a question.

> "Delete runtime configuration: ..."

If the information is readily available, perhaps we should perhaps add the runtime type to this message, e.g. `Delete Kubeflow Pipelines runtime configuration: ...`. This would help with those cases where the runtime configuration name is generic, e.g. `test`.

**Review by lresende — APPROVED** [review]

**Comment by tlzhu19** [comment]
New UI: 
Screen Shot 2021-05-26 at 5 25 28 PM
Screen Shot 2021-05-26 at 5 25 38 PM

Code snippet change to follow others: 
Screen Shot 2021-05-26 at 5 25 51 PM

**Review by ptitzler — APPROVED** [review]
New text is good. Thank you!

**Comment by lresende** [comment]
With the changes on the dialogs, we need to adjust the integration tests like https://github.com/elyra-ai/elyra/blob/dc7c0e43afab0ba3e19311982cc019a7dd2c91cd/tests/integration/codesnippet.ts#L345

**Review by lresende — APPROVED** [review]

**Pull request merged**
