### PR TITLE
Add initial support for supernodes

### PR DESCRIPTION
**Pull request by kevin-bates**
Supernodes are now supported at a basic level.  The UI has been minimally modified to enable their creation.  However, we'll likely want to enhance the use of supernodes.  For example, we might want the various properties, envs, dependencies, to pertain to all nodes in the supernode, etc.  Right now, you're not able to edit the properties of a supernode - at least relative to elyra.

The pipeline submitted to the backend runtime consists of a flattened. pipeline where disjoint pipeline definitions can be executed in parallel.  The presence of a supernode essentially equates to the flattening of its corresponding pipeline reconnected to any external input/output nodes.

Although differences appear significant, much is due to refactoring to handle multiple pipeline definitions and recursion, as well as simplification of helper functions and the addition of type hints.  As a result, you might find it easier to review looking at the code directly rather than the diffs.

Here's an example of a supernode that was executed:
Screen Shot 2020-07-24 at 2 29 48 PM

And here's the corresponding "flattened" representation in kubeflow...
image

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kevin-bates** [comment]
Moving to draft to add some better tests to validate link navigation.

**Comment by kevin-bates** [comment]
Updated pipeline_with_supernode.json to contain a valid pipeline with a supernode taking inputs and producing outputs.  Then updating the supernode test to confirm its structure.

Here's what it looks like:
Screen Shot 2020-07-25 at 7 36 12 AM

**Comment by lresende** [comment]
@marthacryan Could you take a quick look at this regarding the validation of pipelines when supernodes are enabled.

**Comment by kevin-bates** [comment]
@marthacryan - I'm not sure what all the front-end validation consists of, but I'd be happy to help you navigate the weeds of super and binding nodes. It took a fair amount of sitting down with the pipeline JSON to track things down.

**Comment by marthacryan** [comment]
Ok I added some changes to address the issues with validation - someone should definitely play around with it though.

**Comment by marthacryan** [comment]
Here are some pictures of the behavior:
- Collapsed supernode containing invalid nodes (including tooltip and highlighted edges for selected node):
image
- Expanded supernode containing invalid nodes (has the same tooltip message):
image
- Properties option is removed from the context menu of the supernode. Properties option for the supernode's children is still accessible from the context menu of the expanded node as well as in the complete view of the supernode:
image
And the same behavior of automatically re-validating after the properties are updated still works:
image

**Pull request merged**
