### PR TITLE
Fix tag bug

### LINKED ISSUE #2751: Changes to metadata tags do not persist
**Describe the issue**
Metadata tags do not persist when using 3.9.0rc0 and latest master branch. This is an issue both when creating a new tag (it disappears) or attempting to edit existing tags.

**To Reproduce**
1. Go to any metadata instance that has a `tags` field
2. Add a new tag to an instance, and 'Save & Close'
4. Note that tag doesn't appear in dropdown area where tags can be used as filters
5. Open same instance and see that tag doesn't show up in the edit page as well

**Screenshots or log output**
Console logs didn't seem to indicate anything out of the ordinary, nor do the debug logs (below).

<details><summary>Debug Log Output</summary>
<pre>
[D 2022-06-01 12:31:17.662 ElyraApp] Loading metadata instance from cache: 'print'
[D 2022-06-01 12:31:17.663 ServerApp] MetadataHandler: Updating metadata instance 'print' in schemaspace 'code-snippets'...
[D 2022-06-01 12:31:17.663 ElyraApp] Loading metadata instance from cache: 'print'
[D 2022-06-01 12:31:17.666 ElyraApp] Renamed resource for instance 'print' to: '/Users/kierstenstokes/Library/Jupyter/metadata/code-snippets/print.json1654104677.6662002'
[D 2022-06-01 12:31:17.666 ElyraApp] Updated metadata instance: /Users/kierstenstokes/Library/Jupyter/metadata/code-snippets/print.json
[D 2022-06-01 12:31:17.666 ElyraApp] Loading metadata instance from: '/Users/kierstenstokes/Library/Jupyter/metadata/code-snippets/print.json'
[D 2022-06-01 12:31:17.667 ElyraApp] Loading metadata instance from cache: 'print'
</pre>
</details>

**Expected behavior**
Changes to tags should persist 

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.9.0rc0 and latest master
 - Installation source: PyPI for the rc

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #2751. Cleans up metadata editor tag code to fix tag saving bug. 

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by kiersten-stokes — APPROVED** [review]
Functionality looks good to me!

**Review by karlaspuldaro — COMMENTED** [review]
Looks good, tags changes are now being saved as expected, thanks @marthacryan !
I just found a new bug in validating tags - adding empty space(s) tag through the UI cannot be removed and the metadata cannot be saved either.
Let me know if I should open a new issue for this.

**Comment by marthacryan** [comment]
Thanks @kiersten-stokes and @karlaspuldaro for testing it out! @karlaspuldaro I added a fix for the empty spaces bug you found cause it was a quick fix.

**Review by karlaspuldaro — APPROVED** [review]
LGTM. Thx for also addressing the empty tag bug here!

**Pull request merged**
