### PR TITLE
Handle no runtimes configured on run/export/submit 

### LINKED ISSUE #1339: Submit notebook | run pipeline | export pipeline aren't working as expected when no runtime configurations are defined
**Describe the issue**
**Submit notebook | run pipeline | export pipeline** aren't working as expected if no runtime configurations are defined

**To Reproduce**
1. Remove all runtime configurations (e.g. rename the directory where they are stored if you have some defined)
2. Open a notebook
3. Click `Submit notebook`
4. [Usability] Observe the error message. From a user's point of view this is not an error condition. Opportunities for improvement:
    - Rephrase the message text to indicate what the user can do to create a runtime. 
    - Add a link that opens the runtime configuration view OR Add a link that opens the new runtime configuration wizard
   
   image

5. Click `OK`
6. [Error] A dialog is displayed
    image

   image

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2+
 - Operating system: [e.g. macos, linux]
 - Installation source: from source

### LINKED ISSUE #1340: Submit notebook | run pipeline | export pipeline aren't working as expected when only one runtime configuration is defined
**Describe the issue**
Submit notebook | run pipeline | export pipeline aren't working as expected. See steps.

**To Reproduce**
1. Create a single runtime configuration for Apache Airflow
2. Create a notebook
3. Click `Submit notebook`
4. Review the dialog. The `runtime platform` selector displays two entries, even though it is guaranteed that there is no configuration defined for one of them

   image

  Note the problem:
    - The user can select an empty configuration AND submit the notebook
    - Aside: all label values should use the same case

  image

image

**Expected behavior**

- The `runtime type` selector only displays an entry for type(s) for which a configuration has been defined.
- `OK` is only enabled after a runtime configuration has been selected.
- The label values follow the same pattern (not sure what the agreed upon standard is)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1 (any dev build that includes Apache Airflow support and thus supports two runtime types)

### LINKED ISSUE #1391: Runtime should not appear as an option if there are no instances
**Describe the issue**
When choosing to run a pipeline, the user is greeted with a drop-down to select which runtime to run against.  If there are no instances of a given runtime, especially since there's no way to create a runtime instance from that dialog, then I wonder if the runtime should even be selectable.

**To Reproduce**
1. With no instances of Airflow or KFP runtimes present, open a pipeline and run it.
2. Click on a runtime that has no instances.  

**Screenshots or log output**
image

**Expected behavior**
The runtime (Apache Airflow in this case) should not be present or greyed out.

### LINKED ISSUE #1403: Standardize label text  for common label names
**Describe the issue**
Currently the GUI is not consistent with respect to the naming convention that is used to refer to a property. For example, one dialog might refer to `pipeline name`, `runtime`, and `runtime configuration`

image

whereas another might refer to `pipeline name`, `runtime platform`, and `runtime config`. The same applies to capitalization in general, e.g. `Pipeline name` vs `Pipeline Name`.

image

**To Reproduce**
1. Open various dialogs that require the user to choose a runtime configuration

### LINKED ISSUE #1409: Run pipeline dialog window resize issue
**Describe the issue**

The text box size for the pipeline name is fixed length and too short by default:

image

**To Reproduce**
1. Create a pipeline
2. Create runtime configuration
3. Open run pipeline wizard
4. Inspect the input text size

**Expected behavior**

The input text box spans the entire width of the dialog window, just like the select boxes already do.
 
**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1RCx

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fixes #1339 
- [X] Add meaningful tooltip info on submit buttons (notebook and python script)
- [X] Add message to empty runtimes widget
- [X] Add custom dialog button for no runtimes (export pipeline, submit notebook and python script)
- [X] Handle open runtimes widget on submit notebook, python script and pipeline export

image

Fixes #1391 
- [x]  Handle options on run pipeline dialog (when no runtimes is configured)

Fixes #1340
Handle dialog options when only one runtime type is configured:
- [X] On run pipeline dialog
- [X] On export pipeline dialog
- [x] On submit notebook / python script dialog

Fixes #1403 
- [X] Fix dialog label inconsistencies

Fixes #1409 

Test for no runtimes config
- [ ] Add integration tests (submit notebook, submit python script, run pipeline, export pipeline)

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Just to be clear the workflow scenario that triggers the message is:
 - user does not have a runtime configuration defined
 - user tries to submit a notebook, Python script or pipeline
 - message is displayed?
 
If that's the case then the output should describe what cannot be done, why it cannot be done, and what the user can do to resolve the situation, e.g.:

- Title: Cannot submit <notebook | Python script | pipeline>
- Message text: No runtime configuration is defined. Create one and try again.
- Button labels: <Cancel> <Open Runtime Configuration wizard>

**Comment by karlaspuldaro** [comment]
This is how the custom dialog message looks like (export pipeline example):
image

Will resolve conflicting files then this PR should be ready for review.

**Comment by karlaspuldaro** [comment]
This PR is ready for testing/feedback on the items marked as checked on the PR description.
I'll be adding a few more commits related to remaining work for #1340 , back into draft/WIP state for this reason.

**Comment by ajbozarth** [comment]
I've pushed the fix for #1409 but I'm still in the process of actually testing and reviewing the rest of the PR

**Review by lresende — APPROVED** [review]
LGTM, tested in a clean env, and the runtimes side panel and dialogs are working much better now. Also added runtimes only for kfp and tested that airflow was not enabled. Tried submitting pipelines, notebook, python script.

**Comment by ptitzler** [comment]
Fit and finish:  (should be singular)

image

**Comment by ptitzler** [comment]
In the submit dialogs  `Runtime Images:` should be `Runtime Image:` (singular)

image

**Comment by ptitzler** [comment]
In the submit dialogs  `Environmental Variables` should be `Environment Variables:` like it is in the pipeline editor

image

**Comment by ptitzler** [comment]
"Include File Dependencies" (consistent casing)
image

**Comment by ptitzler** [comment]
Aside from the fit and finish issues ^^ the submit/run/export dialogs now appear to work as expected ✅

**Comment by ajbozarth** [comment]
I've tested locally and it lgtm pending Patricks comments

**Comment by lresende** [comment]
Fit and finish suggestions updated:
image

**Pull request merged**
