### PR TITLE
Tweak runtime metadata definitions for Airflow and Kubeflow

### PR DESCRIPTION
**Pull request by ptitzler**
This PR updated the metadata definitions for the KFP and AA runtimes:
- the title now includes the runtime type
- replaced the category name with the official AA name
- made AA UI endpoint property required (the UI fails if one does not enter a URL => https://github.com/elyra-ai/elyra/issues/1307)

image

If AA UI endpoint property is not required this would be broken and a user would not have access to the AA UI from Elyra.

image

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Test failure: 
```
AssertionError: Timed out retrying after 8000ms: Expected to find element: `button.elyra-metadataHeader-button[title="Create new Pipeline runtime configuration"]`, but never found it.
```

**Comment by ptitzler** [comment]
@ajbozarth please make sure these changes are in your PR

**Review by ajbozarth — APPROVED** [review]

**Review by akchinSTC — APPROVED** [review]
LGTM

**Review by kevin-bates — APPROVED** [review]

**Comment by lresende** [comment]
To fix the tests, we need to adjust the `title` at https://github.com/elyra-ai/elyra/blob/08bb75a585dc0fb857b969d6beaad7e93169a7b1/tests/integration/pipeline.ts#L393

**Pull request merged**
