### PR TITLE
Group component properties by inputs and outputs

### LINKED ISSUE #2182: Improve visualization of the custom components properties view
**Is your feature request related to a problem? Please describe.**

We should try to tweak the custom node property panel to
- display fewer (low value) information (e.g. help text for self-explanatory read-only properties)
- clearly separate input and outputs visually (e.g. by creating sections)

Current visualization for a node with just one input and output:

image

The main goal is to avoid (as much as possible) the need for the user to scroll to access properties because they don't fit on the screen. Example: a pipeline contains 10 nodes and each node has multiple input and outputs that [currently] cannot be displayed on a page without a scroll bar. If the user wants to inspect the properties of each node, they might have to scroll back and forth to access the desired information.

**Describe the solution you'd like**

As a starting point for discussions:
 - remove help text for (system properties that are likely self-explanatory - see strikethrough examples below)
 - clearly group inputs and outputs (currently one has to read the description to determine whether a property is an input an and output - ignoring for now that outputs are not editable)
 - avoid line wrapping for certain fields (like `component path`) as long as a user can copy and paste the complete value if desired to save space

image

### PR DESCRIPTION
**Pull request by kiersten-stokes**
Fixes #2182

### What changes were proposed in this pull request?
Changes the palette groups to provide headers for `Inputs`, `Outputs`, and `Component Source` in the component properties panel. The header will not be rendered if there are no properties in that category or if properties are not otherwise exposed (e.g., no outputs are exposed for Airflow components, so the `Output` header is not rendered). 

The new header groups also have their own CSS.

- [x] We may want to remove the `"This is an output of this component"` phrase in the description of outputs.

### How was this pull request tested?

- [x] Update backend tests that check against properties.json

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kiersten-stokes** [comment]
Screenshot of properties panel as of the latest commit:

Screen Shot 2022-01-21 at 3 58 32 PM

**Comment by kiersten-stokes** [comment]
With excess description removed for outputs:

Screen Shot 2022-01-21 at 4 43 16 PM

**Comment by marthacryan** [comment]
This should probably get some backend review but the frontend looks good to me! @ajbozarth @karlaspuldaro Do you have any review on the frontend?

**Comment by ajbozarth** [comment]
Based solely on the screenshots this looks ok, I haven't tried it locally though

**Review by akchinSTC — APPROVED** [review]

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
