### PR TITLE
Add ComponentCache load to relevant pipeline app commands

### LINKED ISSUE #2609: Pipeline CLI: submit does not work for pipelines containing custom components
**Describe the issue**
Trying to run a pipeline that utilizes custom components fails 

```
$ elyra-pipeline submit pipeline-with-custom-components.pipeline  --runtime-config my-runtime-config
```

because the referenced components are not found during validation:
```
Validating pipeline...
 [Error][Download File] - This component was not found in the catalog. Please add it to your component catalog or remove this node from the pipeline 
 [Error][Count Rows] - This component was not found in the catalog. Please add it to your component catalog or remove this node from the pipeline 
 [Error][Truncate File] - This component was not found in the catalog. Please add it to your component catalog or remove this node from the pipeline 

Error: Pipeline validation FAILED. The pipeline was not submitted for execution.
```

As far as I can tell this behavior is not pipeline specific and surfaces even if the pipeline utilizes local component catalogs.

**To Reproduce**
1. Create a pipeline that utilizes one or more custom components
2. Try to run pipeline using `elyra-pipeline submit ...`

**Expected behavior**
Pipeline can be submitted

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7/rc0

### LINKED ISSUE #2612: Pipeline CLI: validation returns unexpected error message
**Describe the issue**

User invokes `elyra-pipeline validate`, specifying a pipeline as input that references custom components. 

```
$ elyra-pipeline validate custom-components.pipeline

────────────────────────────────────────────────────────────────
 Elyra Pipeline Validation
────────────────────────────────────────────────────────────────

Validating pipeline...
 [Error][Download File] - This component was not found in the catalog. Please add it to your component catalog or remove this node from the pipeline 
 [Error][Count Rows] - This component was not found in the catalog. Please add it to your component catalog or remove this node from the pipeline 
 [Error][Truncate File] - This component was not found in the catalog. Please add it to your component catalog or remove this node from the pipeline 

```

Since the user did not specify a runtime configuration, Elyra assumes the runtime type to be 'local'. Since 'local' does not support custom components, the validation error text is misleading.

**To Reproduce**
1. Create a KFP/Airflow pipeline that contains at least one custom component.
2. Run `elyra-pipeline validate`

**Expected behavior**
Validation returns an error indicating that the pipeline's type is not compatible with 'local' runtime.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7/rc0

### PR DESCRIPTION
**Pull request by kiersten-stokes**
Fixes #2609 
Fixes #2612 

### What changes were proposed in this pull request?
This PR adds a load of the components in the component cache for pipeline app tools that need it (`submit`, `export`, and `validate`). Note that this will cause some slowdown for these commands because the cache load must be fully complete before moving on to the relevant task (this is true whether or not that task requires the access of any custom components). The cache load does not happen if the pipeline runtime type is determined to be Generic because, in that case, there should not be any custom components present (validation will still catch this issue appropriately if it is encountered).

Screen Shot 2022-03-29 at 5 51 47 PM

In reviewing this PR, the bug described in #2612 was uncovered. This PR also addresses this issue by adding a new case during pipeline node validation. This new case checks for custom component(s) in a pipeline determined to be of runtime 'local' and issues an error message if a custom component is found.

```
 [Error] - This pipeline contains at least one runtime-specific component, but pipeline runtime is 'local'. Specify a runtime config or remove runtime-specific components from the pipeline 
```

### How was this pull request tested?
Some pipeline app tests are also slowed down by this change when run individually, but execution time for all tests isn't noticeably affected.

A test case was added to `test_pipeline_app.py` that checks for the case where a runtime-specific pipeline is submitted for validation with no runtime-config given. The error mentioned in the above section will be raised in this case.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by kevin-bates — APPROVED** [review]
These changes look good to me - thank you @kiersten-stokes.

EDIT: In taking a closer look at the test failures, it seems as though the cache initialization message is interfering with stdout processing in the tests.  Seems like we should try to make the necessary adjustments for this in this PR.

**Comment by kiersten-stokes** [comment]
> EDIT: In taking a closer look at the test failures, it seems as though the cache initialization message is interfering with stdout processing in the tests. Seems like we should try to make the necessary adjustments for this in this PR.

Totally agree. Luckily, my latest commit where I defer cache load until right before validation seems to have fixed the test failures as well!

**Review by ptitzler — CHANGES_REQUESTED** [review]
The fix does not work for the `validate` command if no runtime config is specified, e.g. 

```
$ elyra-pipeline validate custom-components.pipeline
```

In my tests `custom-components.pipeline` is a KFP pipeline.

Edit: Opened https://github.com/elyra-ai/elyra/issues/2612 for this specific problem.

**Review by kevin-bates — APPROVED** [review]

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
