### PR TITLE
Fixes validation of pipelines that contain both pipeline params and default properties.

### LINKED ISSUE #3190: elyra-pipeline validate CLI command fails for pipelines with parameters and default properties
**Describe the issue**
Running `elyra-pipeline validate` and by extension `elyra-pipeline export` fails silently with pipelines that contain both pipeline parameters and default properties.

**To Reproduce**
1. Create a simple Elyra pipeline with a single node.
2. Add a pipeline parameter in the `Pipeline Parameters` configuration tab.
3. Open the `Pipeline Properties` configuration tab.
4. Save the pipeline, e.g. as `test.pipeline`.
5. Validate the pipeline through the CLI: `elyra-pipeline validate test.pipeline`.

**Screenshots or log output**
The following error message without details is printed after running the above validation command:
<details><summary>Log Output</summary>
<pre>
(app-root) (app-root) elyra-pipeline validate test.pipeline 

────────────────────────────────────────────────────────────────
 Elyra Pipeline Validation
────────────────────────────────────────────────────────────────

Validating pipeline...
Error: Pipeline validation FAILED.
</pre>
</details>

**Expected behavior**
Given that pipelines with parameters and default properties are valid in general, the validation command should resolve without any errors.
In case of actual issues within the pipeline file, there should be detailed information about these issues.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.15.0
 - Installation source: quay.io/opendatahub/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.9
 - Deployment type: Red Hat OpenShift Data Science 1.33.0
 - Operating system: linux

### PR DESCRIPTION
**Pull request by rkpattnaik780**
### What changes were proposed in this pull request?

Fixes validation of pipelines that contain both pipeline parameters and default properties.

Fixes #3190 

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by lresende — APPROVED** [review]

**Comment by lresende** [comment]
Please update/fix the lint issues

**Comment by rkpattnaik780** [comment]
> Please update/fix the lint issues

Done, the `Test Server` was failing for version 3.11, fix for which has been raised in #3197 .

**Review by harshad16 — APPROVED** [review]
Thank you for this PR :100: 
This works like a charm.

```
(app-root) (app-root) elyra-pipeline validate untitled.pipeline 

────────────────────────────────────────────────────────────────
 Elyra Pipeline Validation
────────────────────────────────────────────────────────────────

Validating pipeline...

❯ Pipeline validation SUCCEEDED.
```

**Comment by rkpattnaik780** [comment]
The PR has been rebased and updated to fix the linting issues. All checks are now passing.

Cc @lresende

**Pull request merged**
