### PR TITLE
Improve argument handling in elyra-metadata

### PR DESCRIPTION
**Pull request by kevin-bates**
This pull request addresses two things.
1. It more gracefully handles the issue reported in #2640 in which object-value-handling options (i.e., `--file` and `--json`) do not include a file or JSON value (respectively).
2. It generally makes the equals operator (`=`) optional for options that take values, allowing for better parity with the `elyra-pipeline` CLI application.

One negative test, previously used to ensure the `--name` property was properly handled when there was no `equals` operator, has been repurposed since that is now a valid scenario.  In addition, tests specific to the `--file` and `--json` options have been added with 3 scenarios each: using an equals operator, no equals operator, and a missing value.  It also adjusts an existing test (`test_install_and_replace`) to not use the equals operator.

Resolves: #2640
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by ptitzler — COMMENTED** [review]
Confirmed that the following work as expected:
- `elyra-metadata ... --json` (missing value)
- `elyra-metadata ... --file` (missing value)
- `elyra-metadata ... --json <JSON>` 
- `elyra-metadata ... --json=<JSON>` 
- `elyra-metadata ... --file <PATH>` 
- `elyra-metadata ... --file=<PATH>`

**Comment by kevin-bates** [comment]
This makes sense as part of this effort - I'll take a look.

**Comment by kevin-bates** [comment]
This option is already supported:
```
$ elyra-metadata list runtimes --help

List installed metadata for runtimes.

Options
-------

--json
	List complete instances as JSON
--valid-only
	Only list valid instances (default includes invalid instances)
```
but just isn't listed in the help text when applied to the base command:
```
$ elyra-metadata --help

Manage Elyra metadata.

Subcommands
-----------
Subcommands are launched as `elyra-metadata cmd [args]`. For information on
using subcommand 'cmd', run: `elyra-metadata cmd -h`.

list
    List metadata instances for a given schemaspace.
create
    Create a metadata instance in a given schemaspace.
update
    Update a metadata instance in a given schemaspace.
install
    DEPRECATED. Install a metadata instance into a given schemaspace. Use 'create' or 'update' instead.
remove
    Remove a metadata instance from a given schemaspace.
migrate
    Migrate metadata instances in a given schemaspace.
export
    Export metadata instances in a given schemaspace.
```
@ptitzler - I'll update the usage statement to something like the following (let me know if you prefer a different way to express this)...
```
Subcommands are launched as `elyra-metadata cmd [args]`. For information on
using subcommand 'cmd', run: `elyra-metadata cmd -h` or `elyra-metadata cmd --help`.
```

**Review by ptitzler — APPROVED** [review]
LGTM. Will create a separate PR for doc updates.

**Pull request merged**
