### PR TITLE
Temporary fix to metadata editor display bug

### LINKED ISSUE #2592: Metadata editor field not populating existing metadata instances
**Describe the issue**
When a user opens a previously created metadata instance the editor widget shows mostly empty properties

**To Reproduce**
1. Open an existing metadata instance (of any type except code snippet) in the editor. 

image

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7/master

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #2592. 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by ajbozarth — APPROVED** [review]
LGTM, also wanted to note that this doesn't fix the bug noted in https://github.com/elyra-ai/elyra/issues/2590 so that should still be done at some point

**Comment by lresende** [comment]
@marthacryan as this is a temporary fix, it shouldn't `fix` #2592 in the description?

**Comment by marthacryan** [comment]
> @marthacryan as this is a temporary fix, it shouldn't `fix` #2592 in the description?

@lresende Oh I see what you're saying but it's fixing that bug / issue. It's temporary in that we want to add back in `MainEditorWidget` at some point (probably in my current PR #2464). That's for UI consistency more than for the bug described in that issue though so I don't think we should keep that issue open

**Comment by ajbozarth** [comment]
> as this is a temporary fix, it shouldn't fix https://github.com/elyra-ai/elyra/issues/2592 in the description?

This is actually rolling back a "feature addition" that caused the bug seen in that issue. So it does fix the issue by removing the new unreleased feature. We will then reintroduce the feature along side the new form later on. The feature is pretty minor and was a tiny "nice to have" that I added when I noticed how "easy" it was (which apparently was wrong)

**Pull request merged**
