### PR TITLE
Create Elyra image compatible with Kubeflow notebook launcher

### LINKED ISSUE #1036: Elyra images as notebook-server for kubeflow?
This is more of a query: Are there any images provided for running Elyra as a notebook server on existing kubeflow cluster? Something I can use and customize as well ?

Also if not available do you forsee any issues creating a custom image for Elyra? I see this is a very useful plugin and something that can really be helpful in creating the kubeflow pipeline projects.

Thanks for your help, I went through the documentation and could not find any reference.

### PR DESCRIPTION
**Pull request by akchinSTC**
Patterned this image using the upstream pipeline notebook examples

Fixes #1036

image

- [x] Create image and supporting files and verify metadata and workspace is persisted
- [x] Add documentation on how to add the kubeflow pipeline metadata runtime

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akchinSTC** [comment]
@lresende - looking for input if this is good enough for a first pass, with a tighter integration (discovery of co-located kubeflow deployment) to follow? or do we have to have integration now?

**Review by ptitzler — APPROVED** [review]
Tested the instructions by deploying the 2.1.0 image from the docker hub registry. I did not test the Dockerfile.

**Comment by lresende** [comment]
@akchinSTC this looks nice. It seems that most of what we are doing on the dockerfile is to use the kf image as the base and install Elyra. What if we used the same `elyra/elyra` docker image, and just passed the `FROM` as an argument similar to how we do it [here](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/demo-base/Dockerfile)?

**Comment by akchinSTC** [comment]
@lresende  - I tried out multiple change variations, but have not found one that works yet. 
The biggest issue is that we put any number of our configuration files into the `/home/jovyan' directory as a step in the Dockerfile. Kubeflow notebook server explicitly mounts a volume to that path resulting in everything in that directory in the base layer being wiped at runtime.

**Review by lresende — APPROVED** [review]

**Pull request merged**
