### PR TITLE
Enable debugger on kernel change

### LINKED ISSUE #2902: Changing kernels disables debugging
**Describe the issue**
Selecting another kernel that supports debugging disables the debug button.
change-kernel-bug

One **workaround** to this issue is switching to another tab within jupyterlab and switching back to the python editor (page reload will always select ipykernel by default)

**To Reproduce**
1. Make sure to have other kernel supporting debug installed (eg. xeus-python)
2. Open a Python editor with a few lines of code
3. Notice ipykernel is selected by default and the debug button is enabled
4. Select xeus-python kernel
5. Wait a few seconds and notice the debug button is disabled

**Expected behavior**
The kernel restart does not notify the debugger service that kernel has changed.
Selecting any kernel that supports debugging should notify the UI and enable the debug button accordingly.

**Context information**
 - Elyra version: v3.12.0-dev
 - Installation source: from source
 - Operating system: macos

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fixes #2902 : Changing kernels disables debugging
With this fix, changing the kernel selection to any kernel that supports debugging enables the debug button accordingly.
change-kernel-fix

### What changes were proposed in this pull request?
On kernel change, the kernel was shutdown and restarted, although the debugger service and handlers were not updated for some reason.
A simpler solution was to use the `changeKernel` method instead of `shutdown` then `startKernel`.

Other enhancements:
- Reset run button state after interrupting kernel
- Better handle default kernel selection (not to assume there is a language match with the name property)

### How was this pull request tested?
- Added unit tests for default kernel selection + debugging support

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by karlaspuldaro** [comment]
@lresende this is ready for review :)

**Comment by akchinSTC** [comment]
@karlaspuldaro - if have kernelspec debugger set to false with 
```
 "display_name": "Python 3 - fakecopy",
 "language": "python",
 "metadata": {
  "debugger": false
 }
```
should i still be seeing the debugger icon and the ability to activate it?
image

**Comment by karlaspuldaro** [comment]
@akchinSTC Thanks for checking this case, that should disable the button, we might need to update some frontend handlers still. Marking this back to WIP

**Review by marthacryan — APPROVED** [review]
Code LGTM but I haven't tested locally yet

**Comment by marthacryan** [comment]
Just tried it locally and it's working as expected w/ the xeus kernels and built-in kernels.

**Review by akchinSTC — APPROVED** [review]
ok for this to go in as is with follow up pr on the issue I mentioned

**Comment by karlaspuldaro** [comment]
Follow up issue #2916

**Pull request merged**
