### PR TITLE
Created RuntimeImagesWidget for customized UI

### LINKED ISSUE #581: Link to container image in runtime image configuration

### PR DESCRIPTION
**Pull request by ajbozarth**
With this the Runtime Images UI is permanently added to the sidebar
and includes links to the image repos on DockerHub.

Fixes #581

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Can you please add initial support for the optional registry qualifier, e.g. `docker.io/owner/image:tag` or `quay.io/owner/image:tag`.

> Registry names can also include a port, e.g. `registry.host:port`



Examples:
 - `amancevice/pandas:1.1.1` => no registry specified; default to public DH registry (link to `https://hub.docker.com/r/amancevice/pandas`)
 - `docker.io/amancevice/pandas:1.1.1` => public DH registry (link to `https://hub.docker.com/r/amancevice/pandas`)
 - `quay.io/ptitzler/pandas` => public quay.io registry (link to `https://quay.io/repository/ptitzler/pandas?tab=tags`)

I realize there are potentially many accuracy issues (e.g. we don't know what the default registry is on the cluster where the image is utilized), but we can deal with them once users indicate that the default assumptions listed above are not sufficient.

**Review by ptitzler — CHANGES_REQUESTED** [review]
See above comment regarding initial support for registry names

**Comment by ptitzler** [comment]
Test scenarios:
- [ ] `quay.io/elyra/pandas` (`latest` tag is defined in the registry)
- [ ] `quay.io/elyra/pandas:1.1.1`
- [ ] `amancevice/pandas` (`latest` tag is defined in the registry)
- [ ]  `amancevice/pandas:1.2.3` 
- [ ] `docker.io/amancevice/pandas` (`latest` tag is defined in the registry)
- [ ] `docker.io/amancevice/pandas:1.2.2`

**Comment by ajbozarth** [comment]
@ptitzler I pushed an update addressing your comments at EOD last Friday. If you could take a look

**Review by ptitzler — APPROVED** [review]
Test scenarios for public registries completed LGTM.

**Review by lresende — APPROVED** [review]

**Pull request merged**
