### PR TITLE
Update to use LabIcon

### PR DESCRIPTION
**Pull request by ajbozarth**
This PR is for review purposes only, if approved this will be squashed on the single commit on the `jupyterlab-2.0` branch and followed by a rebase on latest master.

I've updated the remainder of our icon usage to use LabIcon and done some minor UI tweaking alongside the changes. Screenshots for the changes will be included in comments below.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
UI changes to the quick scroll in python editor:
Screen Shot 2020-04-01 at 3 06 28 PM
Screen Shot 2020-04-01 at 3 06 32 PM
Screen Shot 2020-04-01 at 3 06 36 PM
Screen Shot 2020-04-01 at 3 10 19 PM
Screen Shot 2020-04-01 at 3 10 27 PM

**Comment by ajbozarth** [comment]
UI changes to the error dialog:
Screen Shot 2020-04-01 at 3 54 23 PM
Screen Shot 2020-04-01 at 3 54 29 PM
Screen Shot 2020-04-01 at 3 54 34 PM
Screen Shot 2020-04-01 at 3 54 43 PM

**Comment by ajbozarth** [comment]
note that I've changed the UI behavior on the error dialog, now the button has a white background normally and highlights with a darker color on mouse-over. Previously it was that dark color by default and moused over to a lighter grey.

**Comment by akchinSTC** [comment]
[Binder](https://mybinder.org/v2/gh/ajbozarth/elyra/labicon?urlpath=lab/)

**Comment by marthacryan** [comment]
LGTM

**Comment by ajbozarth** [comment]
This has been squashed and merged

**Pull request closed without merging**
