### PR TITLE
Simplify R and Python icon svgs

### LINKED ISSUE #2462: R icon missing intermittently from tile in elyra launch page
**Describe the issue**
See picture
image

**To Reproduce**
1. Install and start elyra
2. Should see missing icon picture in splash

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
R Icon to be visible in tile

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.6.0rc0
 - Installation source: pypi
 - Deployment type: local
 - Operating system: macos

### PR DESCRIPTION
**Pull request by ajbozarth**
The use of `id`s in the svgs causes odd behavior. This addresses
that by simlifying the svg dom, using solid colors, and adding
lab css classes for highlighyting in the file browser.

Fixes #2462

Screen Shot 2022-05-03 at 8 24 35 PM
Screen Shot 2022-05-03 at 8 25 06 PM
Screen Shot 2022-05-03 at 8 25 13 PM

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
For reference when replacing the gradient with solid colors in the R icon I used the solid colors in the useR! conference logo https://www.r-project.org/conferences/

**Comment by ajbozarth** [comment]
Licensing followup after todays scrum:

@lresende I'm trying to figure out how to reference the R logo license in our license file but I can't seem to figure out how to reference a CC-BY-SA 4.0 license similar to how we reference Apache or BSD, any guidance? https://www.r-project.org/logo/

Also if I'm reading https://www.python.org/psf/trademarks/ correctly the python icon can be used "as is" (which ours is visually) as long as it represents code written in python, which ours does. (Also it's a trademark not a license)

**Comment by karlaspuldaro** [comment]
Tested this out locally and it seems to solve the issue!
(The original issue also happens in master dev - in case others wish to test this PR - click some side tab while launcher is open and see the R icon not render in master, but does in this branch).

Waiting on the licensing update before approving this PR.

**Comment by akchinSTC** [comment]
I've added the license information for the R logo in accordance with the CC license instructions here:
https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/

**Review by akchinSTC — APPROVED** [review]

**Review by karlaspuldaro — APPROVED** [review]

**Pull request merged**
