### PR TITLE
[HOTFIX] Fix missing f string typo in operator

### PR DESCRIPTION
**Pull request by akchinSTC**
After formatting with black, missed an f-string typo on this line causing the generic operator to fail.

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by kiersten-stokes — APPROVED** [review]
Good catch! Working for me after some tests with generic operators

**Review by kevin-bates — APPROVED** [review]
Thanks Alan.

**Review by ptitzler — APPROVED** [review]
LGTM as a hotfix. However, we should follow up in the future and harden error detection. Whenever the operator is unable to download the prerequisites, e.g. in https://github.com/elyra-ai/elyra/blob/master/elyra/kfp/operator.py#L178-L179, no error is returned by curl, resulting in downstream errors, such as the one we've just encountered.

**Comment by ptitzler** [comment]
See https://curl.se/docs/manpage.html#--fail-with-body, which should return a non-zero return code and terminate processing early

**Pull request merged**
