### PR TITLE
Add errors to tag editor

### PR DESCRIPTION
**Pull request by marthacryan**
This adds displaying errors to the tag editor. Uses the same css as all the other errors. 
image

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akchinSTC** [comment]
hrmm is this a must have for 3.9? 
wondering if we could somehow display a more helpful message for someone not familiar with regex.

**Comment by akchinSTC** [comment]
if this is just to surface the fact that there is an error though, im ok with it

**Comment by marthacryan** [comment]
@akchinSTC Yeah this isn't super readable but I'm just surfacing the error that rjsf created. It shouldn't actually be surfaced now that we're trimming it with #2768 - are there other cases that could break this pattern?

**Comment by ptitzler** [comment]
> @akchinSTC Yeah this isn't super readable but I'm just surfacing the error that rjsf created. It shouldn't actually be surfaced now that we're trimming it with #2768 - are there other cases that could break this pattern?

It doesn't look like it's working as intended. If a user enters a string with leading/trailing spaces the error message  is surfaced:

image

**Review by ptitzler — APPROVED** [review]
LGTM!

**Pull request merged**
