### PR TITLE
Add left palette option to PipelineEditor props

### PR DESCRIPTION
**Pull request by marthacryan**
Can't be merged until pipeline-editor is released with changes from elyra-ai/pipeline-editor#137. Adds the codesandbox link in place of the new release for testing purposes. 

Todo: 
- [ ] Remove hard-coded "generic" nodes in favor of a "runtime" field in the node definition. 

Generic Pipeline:
image
image

KFP Pipeline:
image
image
image

Airflow Pipeline:
image
image

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by marthacryan** [comment]
@ptitzler You should be able to build this locally normally / binder should work

**Comment by ptitzler** [comment]
Sadly, the binder build fails.

**Comment by akchinSTC** [comment]
@marthacryan - couldnt push to this branch, here is my branch with the fix, seems to be working: 
https://github.com/akchinSTC/elyra/commit/ea1ff73c65af89c345c8adfa6df3ace99782667a

**Comment by marthacryan** [comment]
@ptitzler Just pushed a binder fix, did that work for you?

**Comment by ptitzler** [comment]
> @ptitzler Just pushed a binder fix, does that work for you?

It does now. Thank you!

**Review by ajbozarth — APPROVED** [review]

**Pull request merged**
