### PR TITLE
Code snippets integration tests

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Implements tests described in #533 

- [X] Tests for creating a new code snippet
- [x] Tests for code preview (on expand/collapse)
- [x] Tests for expected buttons to be visible on the display list
- [x] Tests for deleting a snippet
- [x] Tests for editing a snippet
- [x] Tests for inserting a snippet into various widgets

Update: 
- Tests for inserting a snippet into various widgets -> only 1/4 of these tests are enabled. CI failures for inserting snippet into notebook, python editor and markdown files can be investigated in a follow up PR.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
@karlaspuldaro what's the status of this pr?

**Comment by karlaspuldaro** [comment]
@lresende I added the work in progress tag back as I'm looking into some tests failing tests CI.

**Comment by karlaspuldaro** [comment]
In order to get this PR ready to merge, I commented out some failing tests on CI for further investigation as they are non blockers (see follow up issue #1154).
The insert code snippet tests can be uncommented for local dev runs when needed for now.

**Review by lresende — APPROVED** [review]
LGTM, very nice...

**Pull request merged**
