### PR TITLE
Add support for updating env vars

### LINKED ISSUE #710: Pipeline node properties does not recognize new environment variables
Create a notebook with some environment variables in a cell:

```
print(os.getenv('USER', default_value))
print(os.getenv('LOGNAME', default_value))
```

Add node to the pipeline and then go to node properties

image

Add more environment variables to the same or another cell:

```
print(os.getenv('USER', default_value))
print(os.getenv('LOGNAME', default_value))
print(os.getenv('CONDA_DEFAULT_ENV', default_value))
```

Save the notebook, reopen the pipeline and the node properties

image

No changes, this is because we are reading/parsing the env_vars values during node add.

This should be fixed by implementing #957 and then integrating on the UI.

### PR DESCRIPTION
**Pull request by ajbozarth**
PR paired with https://github.com/elyra-ai/pipeline-editor/pull/116

### What changes were proposed in this pull request?
Add support for refreshing the env vars detected in a notebook or script in the properties for a node

The callback function is designed to support all future properties updates, not just env vars
 
Also includes Makefile  and doc updates for supporting parallel development of pipeline-editor

Fixes #710

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
Moving this out of WIP, see comments and discussion on the sister PR  elyra-ai/pipeline-editor#116

**Comment by kevin-bates** [comment]
The CI failures look related to this PR given `onPropertiesUpdateRequested` is being added.
```
Error: src/PipelineEditorWidget.tsx(809,11): error TS2322: Type '{ ref: MutableRefObject<any>; nodes: { op: string; description: string; label: string; labelField: string; fileField: string; fileBased: boolean; extension: string; image: string; properties: { ...; }; }[]; ... 7 more ...; onPropertiesUpdateRequested: (args: any) => Promise<...>; }' is not assignable to type 'IntrinsicAttributes & Props & RefAttributes<unknown>'.
  Property 'onPropertiesUpdateRequested' does not exist on type 'IntrinsicAttributes & Props & RefAttributes<unknown>'.
```

**Comment by ajbozarth** [comment]
> The CI failures look related to this PR given `onPropertiesUpdateRequested` is being added.

Figured out that this is because the CI tests are pulling the release version of `pipeline-editor` not the sister PR code that this PR is dependent on. So CI will continue to fail until that PR is merged and released

**Comment by lresende** [comment]
I can't seem to make my local env to pickup the built package from `pipeline-editor`. I think we might be missing some sort of link location?

**Comment by ajbozarth** [comment]
converted this back to draft because since it will need to wait for a release of pipeline-editor then update the versions prior to merging this. It only works now if you install the sister PR code locally.

**Comment by lresende** [comment]
@ajbozarth Master has been updated with the latest `Pipeline Editor` and this should be good to be rebased and merged.

**Review by lresende — APPROVED** [review]

**Comment by ptitzler** [comment]
This does require a user doc update, doesn't it? How would users know about this new feature?

**Pull request merged**
