### PR TITLE
Update docs to reflect proper generic op output file usage

### PR DESCRIPTION
**Pull request by akchinSTC**
### What changes were proposed in this pull request?

Updated the docs and placeholder text in response to 

https://github.com/elyra-ai/elyra/issues/2789 and 
https://github.com/elyra-ai/elyra/issues/995#issuecomment-715633815

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by ptitzler — APPROVED** [review]
LGTM! Should we perhaps also reference the data volume topic as it provides an alternative for large (in terms of disk size or number of files) outputs ?

**Comment by akchinSTC** [comment]
> LGTM! Should we perhaps also reference the data volume topic as it provides an alternative for large (in terms of disk size or number of files) outputs ?

Im probably going to follow that up in a separate PR since Id like to address the issues brought up by cupdike in https://github.com/elyra-ai/elyra/issues/2794. Maybe updating the best practices doc and explain the diff between the intermediate volume workspace and the output file parameter

**Comment by cupdike** [comment]
Apologies if I am missing context here, but doesn't this suggest that wildcards actually are supported?
https://github.com/elyra-ai/elyra/blob/main/elyra/airflow/bootstrapper.py#L197

**Comment by akchinSTC** [comment]
thank you @cupdike.
@ptitzler, im probably going modify this PR a bit more while fixing #995, since the current documentation is correct (albeit with the bug). Listing files in outputs with wildcards does function correctly, but subsequent child nodes that we pass the wildcard path to cannot properly expand it and grab from s3. 
wondering if we should disable wildcarding for now, so that subsequent nodes are able to proceed and provide guidance on how to properly push/pull artifacts to/from s3 (via compressed archives), or perhaps add the compression steps when wildcards are present to the bootstrapper and make the process transparent ?

**Comment by ptitzler** [comment]
> Listing files in outputs with wildcards does function correctly, but subsequent child nodes that we pass the wildcard path to cannot properly expand it and grab from s3. wondering if we should disable wildcarding for now, so that subsequent nodes are able to proceed 

In a way doing so would result in a breaking change, as there _might_ be users that use this feature to make artifacts available in the last (or only) pipeline node.  
> and provide guidance on how to properly push/pull artifacts to/from s3 (via compressed archives), or perhaps add the compression steps when wildcards are present to the bootstrapper and make the process transparent ?

Should we perhaps we update the best practices document for now and fix the implementation (based on your suggestion) in a future release? We are at the tail end of the 3.10 release and I'm not sure the latter can be handled in time.

**Pull request merged**
