### PR TITLE
Fix Material UI style specificity issues in Metadata Editor

### PR DESCRIPTION
**Pull request by bourdakos1**
TODO:
- [x] remove hardcoded mui css
- [x] update tests that target `Mui-xxx` to `elyra-Mui-xxx` (we should avoid using classnames to target, but that's another issue)

fixes: #1428 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by bourdakos1** [comment]
cypress just bumped from 6.6.0 to 6.7.0 like 8 minutes ago and the package isn't actually available yet, so that's why tests are failing 🙃

**Review by ajbozarth — APPROVED** [review]
I fought hard with @lresende about not naming it `ThemeProvider`, I greatly dislike overloading classnames and feel that it can cause confusion and mixups. But if you believe it is better react practice to overload the name then I'll relent on this.

Otherwise I tested this locally and it looks good. I'll leave it to @marthacryan to confirm this doesn't revert #1425

**Comment by bourdakos1** [comment]
Yea, I normally prefer not to overload classnames, but I think in this case there's not really a great alternative

**Comment by ajbozarth** [comment]
> Yea, I normally prefer not to overload classnames, but I think in this case there's not really a great alternative

@lresende and I went back and forth on names offline for a long while before finally setting on `ThemeComponent` as a decent middle ground given the best name would be to overload `ThemeProvider`.

I would rather leave it as `ThemeComponent` than overloading `ThemeProvider` if you don't have strong opinions on the name.

**Comment by bourdakos1** [comment]
I think it definitely needs to have `Provider` at the end and we shouldn't use `Component` as part of a react component's name, because everything is a component

**Comment by bourdakos1** [comment]
I think `ThemeProvider` is kind of the expected name for theme providers

**Pull request merged**
