### PR TITLE
Update Copyright headers

### LINKED ISSUE #2389: Copyright headers need annual update
Elyra Copyright headers need to be updated to include current year.

As per [this comment](https://github.com/elyra-ai/elyra/pull/2390#issuecomment-1011567436), all other repositories in the elyra org must be updated.

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Closes #2389 
Updates current year to Copyright headers.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
is this a partial change? I would just search/replace the full repo and process the necessary changes. This should also be replicated in all other repositories for the org.

**Review by lresende — CHANGES_REQUESTED** [review]
Please perform the updates in "ALL" files.

**Review by ajbozarth — APPROVED** [review]
trusting you got every file

**Review by lresende — CHANGES_REQUESTED** [review]
Missing a couple of files:
```
grep -ri "Copyright 2018-2021 Elyra Authors"                                                                                                                                    elyra/pr-2390
./elyra/util/gitutil.py:# Copyright 2018-2021 Elyra Authors
./elyra/util/gitlab.py:# Copyright 2018-2021 Elyra Authors
```

**Review by lresende — APPROVED** [review]

**Pull request merged**
