### PR TITLE
Exclude single-line comments from content parsing

### PR DESCRIPTION
**Pull request by kiersten-stokes**
In chatting with @kevin-bates, it was determined that we currently do not exclude commented-out code from content parsing. This PR seeks to fix that problem for single-line comments through the addition of the `_get_line_without_comments` function and a language-specific `_comment_char` variable corresponding to the character that represents the beginning of a *single-line* comment in that language.

Tests will also be updated to reflect this change by including commented-out environment variables in the content to be parsed.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by kevin-bates — COMMENTED** [review]
This looks good.  Thank you.  Just had the one comment about where to locate the attribute.

**Comment by kevin-bates** [comment]
Hmm - the failures are during the linting...
```
flake8 elyra
elyra/pipeline/tests/test_airflow_processor.py:17:1: H216: The unittest.mock module should be used rather than the third party mock package unless actually needed. If so, disable the H216 check in hacking config and ensure mock is declared in the project's requirements.
make: *** [Makefile:81: lint-server] Error 1
```
I want to say @akchinSTC dealt with this somewhere, but I'm not recalling.

**Comment by kiersten-stokes** [comment]
Yes I vaguely remember hearing about that before too. I also just noticed I don’t have a blank line at the end of a few of the test resources, although it looks like that was how it was before so I’m not sure that’s it. But I’ll add those blank lines anyway

**Comment by kiersten-stokes** [comment]
> This looks good. Thank you. Just had the one comment about where to locate the attribute.

@kevin-bates I think you may have closed out the tab where you made the comment before submitting it. I'm guessing maybe put it in the parent class? 😄

**Review by kevin-bates — APPROVED** [review]

**Review by lresende — APPROVED** [review]

**Pull request merged**
