### PR TITLE
Add pipeline description when submitting to KFP

### LINKED ISSUE #799: Add "origin" information to generated pipeline PY/DSL
- Create a basic pipeline (any pipeline will do)
- Run the pipeline
- Open the pipeline in Kubeflow Pipelines
Note that _version source_ and _description_ are currently empty.

image

For the sake of traceability Elyra should (if possible) provide this information to enable Kubeflow Pipelines users to identify the pipeline origin. e.g `Elyra <pipeline name>`

### PR DESCRIPTION
**Pull request by lresende**
With this, the submitted pipeline will have the following summary on the KFP admin UI

image

One thing to have in mind is that, when we start to use versions, the Elyra version might be misleading here, as newer versions might have been submitted with a newer version of Elyra.

Fixes #799

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by kevin-bates — APPROVED** [review]
This is great info - thanks Luciano.

**Comment by ptitzler** [comment]
It'd be great if we could also include the pipeline file name. Since a user can pick any arbitrary pipeline name when a job is submitted, there isn't necessarily a correlation between the pipeline name and the pipeline file name.

Exhibit A - lazy user named ptitzler tends to use pipeline names like these when submitting a job

image

**Comment by lresende** [comment]
Updated:

image

**Comment by ptitzler** [comment]
Would you mind removing the parentheses => "using ... .pipeline" to make this a complete sentence? Other than that the PR LGTM.

**Comment by lresende** [comment]
Updated version. Note that I used simple quotes to wrap the pipeline name in case there are spaces.

image

**Review by ptitzler — APPROVED** [review]
Perfect!

**Pull request merged**
