### PR TITLE
Adding latest version for container images to refresh runtime images

### PR DESCRIPTION
**Pull request by Hema-Mathiyazhagan**
What changes were proposed in this pull request?
found the latest images with curl and updated the json files.#2516
 
How was this pull request tested?
 Testing is in progress with CI build

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kevin-bates** [comment]
The tests are failing due to #2556 and not related to this PR.  However, the validate-images step in CI is also failing.  Look like the `pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime` image [does not have `curl`](https://github.com/elyra-ai/elyra/runs/5538979486?check_suite_focus=true#step:3:36):
```
ERROR: Image pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime did not meet criteria for command: curl
```

**Comment by Hema-Mathiyazhagan** [comment]
> owever, the validate-images step in CI is also failing. Look like

@kevin-bates Thanks for the heads up. I changed the failing images.

**Comment by ptitzler** [comment]
I've only now noticed that the R container image isn't pinned to a specific version, unlike the other images. Can you please also update https://github.com/Hema-Mathiyazhagan/elyra/blob/runtimeimages/etc/config/metadata/runtime-images/r.json#L5 to use `jupyter/r-notebook:r-4.1.2`?

**Comment by kevin-bates** [comment]
Please merge with master to trigger the server-side tests.  Thanks.

**Comment by Hema-Mathiyazhagan** [comment]
> Hello @Hema-Mathiyazhagan, like @kevin-bates noted, we require `curl` for our generic pipelines to work correctly. Is there another pytorch image elsewhere that you could leverage that does include it?

@kevin-bates I checked other pytorch images. But this is the latest of all images with curl

**Comment by kevin-bates** [comment]
Thanks @Hema-Mathiyazhagan.

Looks like one of the pipeline snapshots requires an update as the referenced image is changed: https://github.com/elyra-ai/elyra/runs/5571273681?check_suite_focus=true#step:8:233

Can someone please help with that?  
cc: @karlaspuldaro, @ajbozarth, @marthacryan

**Comment by ajbozarth** [comment]
To fix the snapshot failure you should delete `tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap` and then rerun tests locally `make test` to regenerate the snapshot. Once it's regenerated you just double check that the only diff is the excepted change to runtime image.

**Comment by akchinSTC** [comment]
@Hema-Mathiyazhagan - Hi, I wasnt able unfortunately to reproduce the failing bootstrapper test failures locally that you are experiencing. I can however push the regenerated snapshots based on your PR here for you to get you unblocked?

**Comment by akchinSTC** [comment]
@Hema-Mathiyazhagan - when i was running these tests locally, i noticed that sometimes the backend test resources like JL and minio wouldnt shut down gracefully if an error occured so you may want to scrub your local processes for any running instances that could be holding needed ports hostage. e.g. ps | grep jupyter

**Review by akchinSTC — APPROVED** [review]

**Pull request merged**
