### PR TITLE
Update /recipes/deploying-elyra-with-opendatahub.md

### PR DESCRIPTION
**Pull request by ptitzler**
This PR updates the "Deploying Open Data Hub with Elyra" documentation topic as follows:
 - simplify `kfDef`:
   - remove Spark kustomizations because they are not needed
   - remove `kf-manifests` repository because it is not referenced
   - update manifest repository URL to v1.0.11, which includes Elyra 2.2.4 
 - Remove references to environment variables from spawner dialog description because the code that utilizes the variables does not work (this content can be re-added should the code work in the future - but for now setting the variable does nothing)  
 - misc edits for clarity
 - move images to new topic-specific location
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Opened new requirement https://github.com/elyra-ai/examples/issues/41 that provides a ready-to-use pipeline, which can be used to validate that the setup is correct.

**Comment by ptitzler** [comment]
Ready for review @akchinSTC

**Comment by ptitzler** [comment]
Found a problem while testing the new validation pipeline. One more commit coming.

**Comment by ptitzler** [comment]
Ready for review but publication is on hold due to KF 1.2/OpenShift issue.

**Review by lresende — APPROVED** [review]

**Pull request merged**
