### PR TITLE
Update Python icon to match JupyterLab

### PR DESCRIPTION
**Pull request by ajbozarth**
In https://github.com/jupyterlab/jupyterlab/pull/13035 JupyterLab has updated their python svg to meet the requirements of the PSF Trademark Committee. Though the svg in that PR is very similar to the one Elyra uses, it does have some differences. As such we should switch to using the new icon. 

~For now I've simply updated our svgs to match the new icon, but once that PR is released (It will be in the next 3.X release, timing unknown) we will want to remove our front end svg and replace all references to it with the jupyterlab LabIcon~

I've removed our python LabIcon and updated references to it to use the icon from core. I've also updated the icon served by our backend to use the new svg file as well.

For reference: The updated icon has the correct colors (the Elyra one has a slightly dark shade of yellow) and margins to match other icons in lab
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ajbozarth** [comment]
v3.4.6 has been released, so I will be updating this as stated above

**Comment by ajbozarth** [comment]
I've pushed the updates, this is ready for review now. Screenshot below:
Screen Shot 2022-09-07 at 1 47 20 PM

@ptitzler if you could take a look at this and feel free to push any doc screen shot changes as needed.

**Comment by ptitzler** [comment]
I'm seeing this 

image


For comparison, this is in `main`

image

**Comment by ptitzler** [comment]
The icon colors look different but I expected them to be the same

image

**Comment by ajbozarth** [comment]
> The icon colors look different but I expected them to be the same

Kernels supply their own icon in the form of an encoded png, in this case they are using the official logo which has an opacity gradient. So the SVG file removes the gradient and sets it to the base color, this change/difference was approved by both the PSF Trademark Committee and the core lab devs.

**Review by karlaspuldaro — APPROVED** [review]
LGTM

**Review by ptitzler — APPROVED** [review]
LGTM!

**Comment by ptitzler** [comment]
Looks like you've missed one version bump in https://github.com/ajbozarth/elyra/blob/py_icon/etc/docker/elyra_development/requirements.yml#L5

**Pull request merged**
