### PR TITLE
Add README files to the subdirectories of etc

### LINKED ISSUE #1351: Add READMEs to directories in elyra/etc
**Describe the issue**
The `etc` directory is being used as a catch all location for any misc tools and helper scripts/configs for elyra. These sub-directories have little to no documentation on what they are for or how to relate to the project as a whole.  

**To Reproduce**

**Screenshots or log output**

**Expected behavior**
Document each subdirectory with a README to describe what it does/used for.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Operating system: [e.g. macos, linux]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]

### PR DESCRIPTION
**Pull request by akchinSTC**
These READMEs describe each subdirectory and its purpose within
the project as a whole

Fixes #1351
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akchinSTC** [comment]
@ptitzler - we can work off this as a base

**Comment by ptitzler** [comment]
This is already almost all we need. If we add the subdirectory content from `etc/docker/README.md` to READMEs in the subdirectories then a user would see the summary information when they land in the subdirectory:
 Example:
  - A section in the documentation (https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-in-a-jupyterhub-environment.html#customizing-the-docker-image-to-be-used) links to https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra
  - https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra contains a README.md with the content you already have in the parent readme:
    ```
    Builds the Elyra image for use as standalone or with JupyterHub. See [Deploying Elyra and JupyterHub in a Kubernetes environment](https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-in-a-jupyterhub-environment.html#deploying-elyra-jupyterhub-in-a-kubernetes-environment)
    ```

 Over time we can then add more detailed information as necessary to the README in the sub directory.

**Comment by akchinSTC** [comment]
Kept the parent README in the docker directory.

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
