### PR TITLE
Add default / placeholder to dropdown field in metadata editor

### LINKED ISSUE #1368: Metadata - select box uses hard-wired placeholder
**Describe the issue**

The select box in the KFP runtime configuration appears to be using a hard-wired placeholder text `Create or select  ...` https://github.com/elyra-ai/elyra/blob/master/packages/ui-components/src/DropDown.tsx#L88

image

**To Reproduce**
1. Create a Kubeflow Pipelines runtime configuration
2. Inspect the `Kubeflow Pipelines engine` select box

**Expected behavior**
Scenario 1: The select box input area displays the `default` value (if one is defined) if the user can only choose from a set of predefined options but cannot add an option ("read-only" drop down) https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/kfp.json#L76

Scenario 2: The select box input area displays the `uihints.placeholder` value, if one is defined:
https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/kfp.json#L71 (none is defined yet in this case) and it's an "editable drop down")

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1/master
 - Installation source: from source

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #1368.

* If `uihints.placeholder` is defined, the field will display that as a placeholder. Otherwise, it will use "Create or select <field name>" as a placeholder for dropdowns
* If the schema defines a `default` for a field, an empty field will automatically use that for the value of the field. Otherwise, the field will be empty.

The code snippet language field remains the same:
image

The KFP runtimes editor automatically shows this when creating a new runtime config: 
image

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
In the KFP scenario, a user should not be able to edit the input field - only choose one. Do we need to introduce another property to indicate that the drop down is supposed to be r/o? 

engine_type

**Review by ptitzler — CHANGES_REQUESTED** [review]
See earlier comment about read only behavior

**Comment by ptitzler** [comment]
Not sure why we are not using a basic select list. There's really no need for text input/clear for read-only properties.

simple_select_list

**Comment by marthacryan** [comment]
@ptitzler I was actually just working on adding that for readonly dropdowns! Here's what it looks like now:
select

**Comment by marthacryan** [comment]
Here's the dropdown in runtime images (no default value):
image
image

**Review by ptitzler — APPROVED** [review]
LGTM. Simple and a lot more user friendly.

**Pull request merged**
