### PR TITLE
document system-level environment variables for file-based pipeline nodes

### PR DESCRIPTION
**Pull request by shalberd**
Document system-level environment variables for file-based pipeline nodes at level Jupyterlab, KFP or Airflow runtime, or both.
Follow-up to #3227 

### How was this pull request tested?

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by shalberd** [comment]
I layed this out conceptually in terms of where the system-level envs apply to, i.e. Jupyterlab or at runtime Airflow and KFP or both (scope).

@harshad16 what should I write about ELYRA_WRITABLE_CONTAINER_DIR? This is only actually used in KFP.

**Review by lresende — APPROVED** [review]

**Comment by shalberd** [comment]
@lresende Thank you. Now we just need to pull this, I guess, from readthedocs, which is I guess related to #3205 .
@romeokienzler FYI

**Comment by lresende** [comment]
#3245 should fix the doc build

**Comment by lresende** [comment]
https://elyra.readthedocs.io/en/latest/user_guide/env-variables-file-based-nodes.html

**Pull request merged**
