### PR TITLE
Remove support for deprecated `component-registries` schemaspace

### LINKED ISSUE #2405: Remove support for the deprecated `component-registries` schemaspace
**Is your feature request related to a problem? Please describe.**
The `component-registries` schemaspace has been deprecated as of 3.3, at which time it was replaced by the `component-catalogs` schemaspace. A `migrate` script was also provided (via the CLI) that converted a user's existing `component-registries` instances into `component-catalog` instances. We expect that most people that had user-created `component-registries` instances have, by now, migrated those instances and that support can be dropped.

Note that a user upgrading directly from Elyra < v3.3 to a version that no longer supports this schemaspace will not see any of their instances and will need to install a down-level release in order to migrate to `component-catalogs`.

This will likely also require documentation changes.

**Describe the solution you'd like**
Completely remove support for and references to the `component-registries` schemaspace.

**Describe alternatives you've considered**
Leave as-is until a major release.

### PR DESCRIPTION
**Pull request by kiersten-stokes**
Fixes #2405

### What changes were proposed in this pull request?
This PR removes all support for the `component-registries` schemaspace, e.g. removes the `ComponentRegistries` `Schemaspace` and the `ComponentRegistriesSchema` `SchemasProvider` classes and the `component-registry.json` schema file.

Also updates the documentation to note the need to install a down-level release to migrate `component-registries` schema instances to `component-catalog` schema instances when updating Elyra from <3.3 to 3.7+

### How was this pull request tested?
Tests did not reference `component-registries` schemaspace since it has been deprecated for a few releases now.

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by lresende — APPROVED** [review]
Approving in support of removing component-registries, but haven't tested.

**Comment by kevin-bates** [comment]
I think if we were to follow semantic versioning convention, this kind of change would need to wait until a major release (although I believe I'm on record as suggesting its removal in 3.5 :smile:).   I'd prefer we drop `component-registeries` but also feel this is the kind of thing that could upset folks that were happily using 3.2 and happen to jump to 3.7.  At least in a jump to 4.0 (from 3.2) we'd have a basis for requiring a down-level installation of 3.3+, whereas, with a ~=3.3 install, it's a tougher argument.

I'm happy to go with the flow if others believe we should go ahead and drop `component-registries`.  If we do decide to hold off until 4.0, I think the doc update of the first paragraph - essentially rephrasing things to use past-tense should be merged.

**Comment by lresende** [comment]
I think we decided to do it now because we were saying `custom components` were still `experimental`.

**Review by kevin-bates — APPROVED** [review]
@lresende - [thanks for the reminder](https://github.com/elyra-ai/elyra/pull/2497#issuecomment-1048247811) regarding our previous discussion.

LGTM - thank you @kiersten-stokes!

**Pull request merged**
